// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module AsyncQueueSource(
  input         clock,
                reset,
  output        io_enq_ready,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  input         io_enq_valid,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  input  [2:0]  io_enq_bits_opcode,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  input  [1:0]  io_enq_bits_param,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  input  [3:0]  io_enq_bits_size,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  input  [5:0]  io_enq_bits_source,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  input  [2:0]  io_enq_bits_sink,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  input         io_enq_bits_denied,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  input  [63:0] io_enq_bits_data,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  input         io_enq_bits_corrupt,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_0_opcode,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [1:0]  io_async_mem_0_param,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [3:0]  io_async_mem_0_size,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [5:0]  io_async_mem_0_source,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_0_sink,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output        io_async_mem_0_denied,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [63:0] io_async_mem_0_data,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output        io_async_mem_0_corrupt,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_1_opcode,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [1:0]  io_async_mem_1_param,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [3:0]  io_async_mem_1_size,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [5:0]  io_async_mem_1_source,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_1_sink,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output        io_async_mem_1_denied,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [63:0] io_async_mem_1_data,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output        io_async_mem_1_corrupt,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_2_opcode,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [1:0]  io_async_mem_2_param,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [3:0]  io_async_mem_2_size,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [5:0]  io_async_mem_2_source,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_2_sink,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output        io_async_mem_2_denied,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [63:0] io_async_mem_2_data,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output        io_async_mem_2_corrupt,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_3_opcode,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [1:0]  io_async_mem_3_param,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [3:0]  io_async_mem_3_size,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [5:0]  io_async_mem_3_source,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_3_sink,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output        io_async_mem_3_denied,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [63:0] io_async_mem_3_data,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output        io_async_mem_3_corrupt,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_4_opcode,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [1:0]  io_async_mem_4_param,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [3:0]  io_async_mem_4_size,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [5:0]  io_async_mem_4_source,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_4_sink,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output        io_async_mem_4_denied,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [63:0] io_async_mem_4_data,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output        io_async_mem_4_corrupt,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_5_opcode,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [1:0]  io_async_mem_5_param,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [3:0]  io_async_mem_5_size,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [5:0]  io_async_mem_5_source,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_5_sink,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output        io_async_mem_5_denied,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [63:0] io_async_mem_5_data,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output        io_async_mem_5_corrupt,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_6_opcode,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [1:0]  io_async_mem_6_param,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [3:0]  io_async_mem_6_size,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [5:0]  io_async_mem_6_source,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_6_sink,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output        io_async_mem_6_denied,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [63:0] io_async_mem_6_data,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output        io_async_mem_6_corrupt,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_7_opcode,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [1:0]  io_async_mem_7_param,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [3:0]  io_async_mem_7_size,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [5:0]  io_async_mem_7_source,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_7_sink,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output        io_async_mem_7_denied,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [63:0] io_async_mem_7_data,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output        io_async_mem_7_corrupt,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  input  [3:0]  io_async_ridx,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [3:0]  io_async_widx,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  input         io_async_safe_ridx_valid,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output        io_async_safe_widx_valid,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
                io_async_safe_source_reset_n,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  input         io_async_safe_sink_reset_n	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
);

  wire        _io_enq_ready_output;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:89:29]
  wire        _sink_valid_io_out;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:104:30]
  wire        _sink_extend_io_out;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:103:30]
  wire        _source_valid_0_io_out;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:100:32]
  wire [3:0]  _ridx_ridx_gray_io_q;	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  reg  [2:0]  mem_0_opcode;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [1:0]  mem_0_param;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_0_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [5:0]  mem_0_source;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_0_sink;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg         mem_0_denied;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [63:0] mem_0_data;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg         mem_0_corrupt;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_1_opcode;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [1:0]  mem_1_param;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_1_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [5:0]  mem_1_source;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_1_sink;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg         mem_1_denied;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [63:0] mem_1_data;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg         mem_1_corrupt;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_2_opcode;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [1:0]  mem_2_param;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_2_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [5:0]  mem_2_source;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_2_sink;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg         mem_2_denied;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [63:0] mem_2_data;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg         mem_2_corrupt;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_3_opcode;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [1:0]  mem_3_param;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_3_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [5:0]  mem_3_source;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_3_sink;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg         mem_3_denied;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [63:0] mem_3_data;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg         mem_3_corrupt;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_4_opcode;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [1:0]  mem_4_param;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_4_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [5:0]  mem_4_source;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_4_sink;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg         mem_4_denied;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [63:0] mem_4_data;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg         mem_4_corrupt;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_5_opcode;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [1:0]  mem_5_param;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_5_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [5:0]  mem_5_source;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_5_sink;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg         mem_5_denied;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [63:0] mem_5_data;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg         mem_5_corrupt;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_6_opcode;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [1:0]  mem_6_param;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_6_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [5:0]  mem_6_source;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_6_sink;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg         mem_6_denied;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [63:0] mem_6_data;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg         mem_6_corrupt;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_7_opcode;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [1:0]  mem_7_param;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_7_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [5:0]  mem_7_source;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_7_sink;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg         mem_7_denied;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [63:0] mem_7_data;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg         mem_7_corrupt;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  wire        _widx_T_1 = _io_enq_ready_output & io_enq_valid;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:89:29, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  reg  [3:0]  widx_widx_bin;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:52:25]
  reg         ready_reg;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:88:56]
  assign _io_enq_ready_output = ready_reg & _sink_valid_io_out;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:88:56, :89:29, :104:30]
  reg  [3:0]  widx_gray;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:91:55]
  wire [2:0]  index = widx_gray[2:0] ^ {widx_gray[3], 2'h0};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:85:{52,64,80,93}, :91:55]
  always @(posedge clock) begin
    if (_widx_T_1 & index == 3'h0) begin	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:52:25, :80:16, :85:64, :86:{22,35}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      mem_0_opcode <= io_enq_bits_opcode;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_0_param <= io_enq_bits_param;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_0_size <= io_enq_bits_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_0_source <= io_enq_bits_source;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_0_sink <= io_enq_bits_sink;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_0_denied <= io_enq_bits_denied;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_0_data <= io_enq_bits_data;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_0_corrupt <= io_enq_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
    end
    if (_widx_T_1 & index == 3'h1) begin	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16, :85:64, :86:{22,35}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      mem_1_opcode <= io_enq_bits_opcode;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_1_param <= io_enq_bits_param;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_1_size <= io_enq_bits_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_1_source <= io_enq_bits_source;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_1_sink <= io_enq_bits_sink;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_1_denied <= io_enq_bits_denied;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_1_data <= io_enq_bits_data;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_1_corrupt <= io_enq_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
    end
    if (_widx_T_1 & index == 3'h2) begin	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16, :85:64, :86:{22,35}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      mem_2_opcode <= io_enq_bits_opcode;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_2_param <= io_enq_bits_param;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_2_size <= io_enq_bits_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_2_source <= io_enq_bits_source;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_2_sink <= io_enq_bits_sink;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_2_denied <= io_enq_bits_denied;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_2_data <= io_enq_bits_data;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_2_corrupt <= io_enq_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
    end
    if (_widx_T_1 & index == 3'h3) begin	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16, :85:64, :86:{22,35}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      mem_3_opcode <= io_enq_bits_opcode;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_3_param <= io_enq_bits_param;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_3_size <= io_enq_bits_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_3_source <= io_enq_bits_source;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_3_sink <= io_enq_bits_sink;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_3_denied <= io_enq_bits_denied;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_3_data <= io_enq_bits_data;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_3_corrupt <= io_enq_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
    end
    if (_widx_T_1 & index == 3'h4) begin	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16, :85:64, :86:{22,35}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      mem_4_opcode <= io_enq_bits_opcode;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_4_param <= io_enq_bits_param;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_4_size <= io_enq_bits_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_4_source <= io_enq_bits_source;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_4_sink <= io_enq_bits_sink;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_4_denied <= io_enq_bits_denied;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_4_data <= io_enq_bits_data;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_4_corrupt <= io_enq_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
    end
    if (_widx_T_1 & index == 3'h5) begin	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16, :85:64, :86:{22,35}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      mem_5_opcode <= io_enq_bits_opcode;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_5_param <= io_enq_bits_param;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_5_size <= io_enq_bits_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_5_source <= io_enq_bits_source;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_5_sink <= io_enq_bits_sink;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_5_denied <= io_enq_bits_denied;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_5_data <= io_enq_bits_data;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_5_corrupt <= io_enq_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
    end
    if (_widx_T_1 & index == 3'h6) begin	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16, :85:64, :86:{22,35}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      mem_6_opcode <= io_enq_bits_opcode;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_6_param <= io_enq_bits_param;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_6_size <= io_enq_bits_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_6_source <= io_enq_bits_source;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_6_sink <= io_enq_bits_sink;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_6_denied <= io_enq_bits_denied;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_6_data <= io_enq_bits_data;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_6_corrupt <= io_enq_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
    end
    if (_widx_T_1 & (&index)) begin	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16, :85:64, :86:{22,35}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      mem_7_opcode <= io_enq_bits_opcode;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_7_param <= io_enq_bits_param;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_7_size <= io_enq_bits_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_7_source <= io_enq_bits_source;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_7_sink <= io_enq_bits_sink;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_7_denied <= io_enq_bits_denied;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_7_data <= io_enq_bits_data;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_7_corrupt <= io_enq_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
    end
  end // always @(posedge)
  wire [3:0]  _widx_incremented_T = widx_widx_bin + {3'h0, _widx_T_1};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:52:25, :53:43, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  wire [3:0]  widx_incremented = _sink_valid_io_out ? _widx_incremented_T : 4'h0;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:53:{23,43}, :104:30]
  wire [3:0]  widx = {widx_incremented[3], widx_incremented[2:0] ^ widx_incremented[3:1]};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:53:23, :54:{17,32}]
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      widx_widx_bin <= 4'h0;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:52:25, :53:23]
      ready_reg <= 1'h0;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16, :88:56]
      widx_gray <= 4'h0;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:53:23, :91:55]
    end
    else begin
      if (_sink_valid_io_out)	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:104:30]
        widx_widx_bin <= _widx_incremented_T;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:52:25, :53:43]
      else	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:104:30]
        widx_widx_bin <= 4'h0;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:52:25, :53:23]
      ready_reg <= _sink_valid_io_out & widx != (_ridx_ridx_gray_io_q ^ 4'hC);	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:54:17, :83:{26,34,44}, :88:56, :104:30, generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
      widx_gray <= widx;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:54:17, :91:55]
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:21];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [4:0] i = 5'h0; i < 5'h16; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        mem_0_opcode = _RANDOM[5'h0][2:0];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_0_param = _RANDOM[5'h0][4:3];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_0_size = _RANDOM[5'h0][8:5];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_0_source = _RANDOM[5'h0][14:9];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_0_sink = _RANDOM[5'h0][17:15];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_0_denied = _RANDOM[5'h0][18];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_0_data = {_RANDOM[5'h0][31:19], _RANDOM[5'h1], _RANDOM[5'h2][18:0]};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_0_corrupt = _RANDOM[5'h2][19];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_1_opcode = _RANDOM[5'h2][22:20];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_1_param = _RANDOM[5'h2][24:23];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_1_size = _RANDOM[5'h2][28:25];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_1_source = {_RANDOM[5'h2][31:29], _RANDOM[5'h3][2:0]};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_1_sink = _RANDOM[5'h3][5:3];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_1_denied = _RANDOM[5'h3][6];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_1_data = {_RANDOM[5'h3][31:7], _RANDOM[5'h4], _RANDOM[5'h5][6:0]};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_1_corrupt = _RANDOM[5'h5][7];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_2_opcode = _RANDOM[5'h5][10:8];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_2_param = _RANDOM[5'h5][12:11];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_2_size = _RANDOM[5'h5][16:13];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_2_source = _RANDOM[5'h5][22:17];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_2_sink = _RANDOM[5'h5][25:23];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_2_denied = _RANDOM[5'h5][26];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_2_data = {_RANDOM[5'h5][31:27], _RANDOM[5'h6], _RANDOM[5'h7][26:0]};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_2_corrupt = _RANDOM[5'h7][27];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_3_opcode = _RANDOM[5'h7][30:28];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_3_param = {_RANDOM[5'h7][31], _RANDOM[5'h8][0]};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_3_size = _RANDOM[5'h8][4:1];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_3_source = _RANDOM[5'h8][10:5];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_3_sink = _RANDOM[5'h8][13:11];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_3_denied = _RANDOM[5'h8][14];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_3_data = {_RANDOM[5'h8][31:15], _RANDOM[5'h9], _RANDOM[5'hA][14:0]};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_3_corrupt = _RANDOM[5'hA][15];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_4_opcode = _RANDOM[5'hA][18:16];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_4_param = _RANDOM[5'hA][20:19];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_4_size = _RANDOM[5'hA][24:21];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_4_source = _RANDOM[5'hA][30:25];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_4_sink = {_RANDOM[5'hA][31], _RANDOM[5'hB][1:0]};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_4_denied = _RANDOM[5'hB][2];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_4_data = {_RANDOM[5'hB][31:3], _RANDOM[5'hC], _RANDOM[5'hD][2:0]};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_4_corrupt = _RANDOM[5'hD][3];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_5_opcode = _RANDOM[5'hD][6:4];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_5_param = _RANDOM[5'hD][8:7];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_5_size = _RANDOM[5'hD][12:9];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_5_source = _RANDOM[5'hD][18:13];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_5_sink = _RANDOM[5'hD][21:19];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_5_denied = _RANDOM[5'hD][22];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_5_data = {_RANDOM[5'hD][31:23], _RANDOM[5'hE], _RANDOM[5'hF][22:0]};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_5_corrupt = _RANDOM[5'hF][23];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_6_opcode = _RANDOM[5'hF][26:24];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_6_param = _RANDOM[5'hF][28:27];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_6_size = {_RANDOM[5'hF][31:29], _RANDOM[5'h10][0]};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_6_source = _RANDOM[5'h10][6:1];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_6_sink = _RANDOM[5'h10][9:7];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_6_denied = _RANDOM[5'h10][10];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_6_data = {_RANDOM[5'h10][31:11], _RANDOM[5'h11], _RANDOM[5'h12][10:0]};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_6_corrupt = _RANDOM[5'h12][11];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_7_opcode = _RANDOM[5'h12][14:12];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_7_param = _RANDOM[5'h12][16:15];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_7_size = _RANDOM[5'h12][20:17];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_7_source = _RANDOM[5'h12][26:21];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_7_sink = _RANDOM[5'h12][29:27];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_7_denied = _RANDOM[5'h12][30];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_7_data = {_RANDOM[5'h12][31], _RANDOM[5'h13], _RANDOM[5'h14][30:0]};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_7_corrupt = _RANDOM[5'h14][31];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        widx_widx_bin = _RANDOM[5'h15][3:0];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:52:25]
        ready_reg = _RANDOM[5'h15][4];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:52:25, :88:56]
        widx_gray = _RANDOM[5'h15][8:5];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:52:25, :91:55]
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        widx_widx_bin = 4'h0;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:52:25, :53:23]
        ready_reg = 1'h0;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16, :88:56]
        widx_gray = 4'h0;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:53:23, :91:55]
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  AsyncResetSynchronizerShiftReg_w4_d3_i0 ridx_ridx_gray (	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
    .clock (clock),
    .reset (reset),
    .io_d  (io_async_ridx),
    .io_q  (_ridx_ridx_gray_io_q)
  );
  AsyncValidSync source_valid_0 (	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:100:32]
    .io_in  (1'h1),	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:79:28]
    .io_out (_source_valid_0_io_out),
    .clock  (clock),
    .reset  (reset | ~io_async_safe_sink_reset_n)	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:105:{43,46}]
  );
  AsyncValidSync source_valid_1 (	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:101:32]
    .io_in  (_source_valid_0_io_out),	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:100:32]
    .io_out (io_async_safe_widx_valid),
    .clock  (clock),
    .reset  (reset | ~io_async_safe_sink_reset_n)	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:105:46, :106:43]
  );
  AsyncValidSync sink_extend (	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:103:30]
    .io_in  (io_async_safe_ridx_valid),
    .io_out (_sink_extend_io_out),
    .clock  (clock),
    .reset  (reset | ~io_async_safe_sink_reset_n)	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:105:46, :107:43]
  );
  AsyncValidSync sink_valid (	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:104:30]
    .io_in  (_sink_extend_io_out),	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:103:30]
    .io_out (_sink_valid_io_out),
    .clock  (clock),
    .reset  (reset)
  );
  assign io_enq_ready = _io_enq_ready_output;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:89:29]
  assign io_async_mem_0_opcode = mem_0_opcode;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_0_param = mem_0_param;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_0_size = mem_0_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_0_source = mem_0_source;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_0_sink = mem_0_sink;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_0_denied = mem_0_denied;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_0_data = mem_0_data;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_0_corrupt = mem_0_corrupt;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_1_opcode = mem_1_opcode;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_1_param = mem_1_param;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_1_size = mem_1_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_1_source = mem_1_source;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_1_sink = mem_1_sink;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_1_denied = mem_1_denied;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_1_data = mem_1_data;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_1_corrupt = mem_1_corrupt;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_2_opcode = mem_2_opcode;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_2_param = mem_2_param;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_2_size = mem_2_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_2_source = mem_2_source;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_2_sink = mem_2_sink;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_2_denied = mem_2_denied;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_2_data = mem_2_data;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_2_corrupt = mem_2_corrupt;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_3_opcode = mem_3_opcode;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_3_param = mem_3_param;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_3_size = mem_3_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_3_source = mem_3_source;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_3_sink = mem_3_sink;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_3_denied = mem_3_denied;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_3_data = mem_3_data;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_3_corrupt = mem_3_corrupt;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_4_opcode = mem_4_opcode;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_4_param = mem_4_param;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_4_size = mem_4_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_4_source = mem_4_source;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_4_sink = mem_4_sink;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_4_denied = mem_4_denied;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_4_data = mem_4_data;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_4_corrupt = mem_4_corrupt;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_5_opcode = mem_5_opcode;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_5_param = mem_5_param;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_5_size = mem_5_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_5_source = mem_5_source;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_5_sink = mem_5_sink;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_5_denied = mem_5_denied;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_5_data = mem_5_data;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_5_corrupt = mem_5_corrupt;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_6_opcode = mem_6_opcode;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_6_param = mem_6_param;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_6_size = mem_6_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_6_source = mem_6_source;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_6_sink = mem_6_sink;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_6_denied = mem_6_denied;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_6_data = mem_6_data;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_6_corrupt = mem_6_corrupt;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_7_opcode = mem_7_opcode;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_7_param = mem_7_param;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_7_size = mem_7_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_7_source = mem_7_source;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_7_sink = mem_7_sink;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_7_denied = mem_7_denied;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_7_data = mem_7_data;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_7_corrupt = mem_7_corrupt;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_widx = widx_gray;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:91:55]
  assign io_async_safe_source_reset_n = ~reset;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:121:27]
endmodule

