// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module MSHR_23(
  input         clock,
                reset,
                io_req_pri_val,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output        io_req_pri_rdy,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  input         io_req_sec_val,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output        io_req_sec_rdy,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  input  [39:0] io_req_bits_addr,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  input  [8:0]  io_req_bits_tag,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  input  [4:0]  io_req_bits_cmd,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  input  [1:0]  io_req_bits_size,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  input         io_req_bits_signed,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  input  [1:0]  io_req_bits_dprv,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  input         io_req_bits_dv,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
                io_req_bits_phys,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
                io_req_bits_no_alloc,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
                io_req_bits_no_xcpt,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  input  [4:0]  io_req_bits_sdq_id,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  input         io_req_bits_tag_match,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  input  [1:0]  io_req_bits_old_meta_coh_state,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  input  [19:0] io_req_bits_old_meta_tag,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  input  [3:0]  io_req_bits_way_en,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output        io_idx_match,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output [19:0] io_tag,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  input         io_mem_acquire_ready,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output        io_mem_acquire_valid,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output [2:0]  io_mem_acquire_bits_param,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output [31:0] io_mem_acquire_bits_address,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  input         io_mem_grant_valid,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  input  [2:0]  io_mem_grant_bits_opcode,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  input  [1:0]  io_mem_grant_bits_param,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  input  [3:0]  io_mem_grant_bits_size,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  input  [2:0]  io_mem_grant_bits_sink,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  input         io_mem_finish_ready,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output        io_mem_finish_valid,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output [2:0]  io_mem_finish_bits_sink,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output [3:0]  io_refill_way_en,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output [11:0] io_refill_addr,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  input         io_meta_read_ready,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output        io_meta_read_valid,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output [5:0]  io_meta_read_bits_idx,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  input         io_meta_write_ready,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output        io_meta_write_valid,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output [5:0]  io_meta_write_bits_idx,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output [3:0]  io_meta_write_bits_way_en,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output [1:0]  io_meta_write_bits_data_coh_state,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output [19:0] io_meta_write_bits_data_tag,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  input         io_replay_ready,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output        io_replay_valid,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output [39:0] io_replay_bits_addr,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output [8:0]  io_replay_bits_tag,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output [4:0]  io_replay_bits_cmd,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output [1:0]  io_replay_bits_size,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output        io_replay_bits_signed,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output [1:0]  io_replay_bits_dprv,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output        io_replay_bits_dv,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output [4:0]  io_replay_bits_sdq_id,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  input         io_wb_req_ready,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output        io_wb_req_valid,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output [19:0] io_wb_req_bits_tag,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output [5:0]  io_wb_req_bits_idx,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output [2:0]  io_wb_req_bits_param,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output [3:0]  io_wb_req_bits_way_en,	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
  output        io_probe_rdy	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
);

  wire             _io_req_pri_rdy_output;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:197:75]
  wire             _grantackq_io_enq_ready;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:257:25]
  wire             _grantackq_io_deq_valid;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:257:25]
  wire             _rpq_io_enq_ready;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:194:19]
  wire             _rpq_io_deq_valid;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:194:19]
  wire [39:0]      _rpq_io_deq_bits_addr;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:194:19]
  wire [4:0]       _rpq_io_deq_bits_cmd;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:194:19]
  reg  [3:0]       state;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:168:22]
  reg  [39:0]      req_addr;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16]
  reg  [4:0]       req_cmd;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16]
  reg  [1:0]       req_old_meta_coh_state;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16]
  reg  [19:0]      req_old_meta_tag;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16]
  reg  [3:0]       req_way_en;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16]
  wire             idx_match = req_addr[11:6] == io_req_bits_addr[11:6];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, :171:25, :174:{27,47}]
  reg  [1:0]       new_coh_state;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:176:24]
  wire             _needs_second_acq_T_27 = req_cmd == 5'h1;	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:86:32, generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16]
  wire             _needs_second_acq_T_28 = req_cmd == 5'h11;	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:86:49, generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16]
  wire             _needs_second_acq_T_30 = req_cmd == 5'h7;	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:86:66, generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16]
  wire             _needs_second_acq_T_32 = req_cmd == 5'h4;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire             _needs_second_acq_T_33 = req_cmd == 5'h9;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire             _needs_second_acq_T_34 = req_cmd == 5'hA;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire             _needs_second_acq_T_35 = req_cmd == 5'hB;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire             _needs_second_acq_T_39 = req_cmd == 5'h8;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire             _needs_second_acq_T_40 = req_cmd == 5'hC;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire             _needs_second_acq_T_41 = req_cmd == 5'hD;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire             _needs_second_acq_T_42 = req_cmd == 5'hE;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire             _needs_second_acq_T_43 = req_cmd == 5'hF;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire             _needs_second_acq_T_50 = req_cmd == 5'h3;	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:87:54, generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16]
  wire             _needs_second_acq_T_52 = req_cmd == 5'h6;	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:87:71, generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16]
  wire [3:0]       _grow_param_T = {_needs_second_acq_T_27 | _needs_second_acq_T_28 | _needs_second_acq_T_30 | _needs_second_acq_T_32 | _needs_second_acq_T_33 | _needs_second_acq_T_34 | _needs_second_acq_T_35 | _needs_second_acq_T_39 | _needs_second_acq_T_40 | _needs_second_acq_T_41 | _needs_second_acq_T_42 | _needs_second_acq_T_43, _needs_second_acq_T_27 | _needs_second_acq_T_28 | _needs_second_acq_T_30 | _needs_second_acq_T_32 | _needs_second_acq_T_33 | _needs_second_acq_T_34 | _needs_second_acq_T_35 | _needs_second_acq_T_39 | _needs_second_acq_T_40 | _needs_second_acq_T_41 | _needs_second_acq_T_42 | _needs_second_acq_T_43 | _needs_second_acq_T_50 | _needs_second_acq_T_52, new_coh_state};	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:86:{32,49,66,76}, :87:{54,64,71}, generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:176:24, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:58:19, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire [1:0]       _grow_param_T_27 = {1'h0, _grow_param_T == 4'hC};	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:58:19, generators/rocket-chip/src/main/scala/util/Misc.scala:35:36, :49:20, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire [15:0][1:0] _GEN = {{2'h3}, {2'h3}, {2'h2}, {_grow_param_T_27}, {_grow_param_T_27}, {_grow_param_T_27}, {_grow_param_T_27}, {_grow_param_T_27}, {2'h3}, {2'h2}, {2'h2}, {2'h1}, {2'h3}, {2'h2}, {2'h1}, {2'h0}};	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:35:36, :49:20]
  wire             _c_cat_T_123 = io_req_bits_cmd == 5'h1;	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:86:32]
  wire             _c_cat_T_124 = io_req_bits_cmd == 5'h11;	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:86:49]
  wire             _c_cat_T_126 = io_req_bits_cmd == 5'h7;	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:86:66]
  wire             _c_cat_T_128 = io_req_bits_cmd == 5'h4;	// @[generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire             _c_cat_T_129 = io_req_bits_cmd == 5'h9;	// @[generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire             _c_cat_T_130 = io_req_bits_cmd == 5'hA;	// @[generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire             _c_cat_T_131 = io_req_bits_cmd == 5'hB;	// @[generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire             _c_cat_T_135 = io_req_bits_cmd == 5'h8;	// @[generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire             _c_cat_T_136 = io_req_bits_cmd == 5'hC;	// @[generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire             _c_cat_T_137 = io_req_bits_cmd == 5'hD;	// @[generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire             _c_cat_T_138 = io_req_bits_cmd == 5'hE;	// @[generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire             _c_cat_T_139 = io_req_bits_cmd == 5'hF;	// @[generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire             _c_cat_T_146 = io_req_bits_cmd == 5'h3;	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:87:54]
  wire             _c_cat_T_148 = io_req_bits_cmd == 5'h6;	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:87:71]
  wire [26:0]      _beats1_decode_T_1 = 27'hFFF << io_mem_grant_bits_size;	// @[generators/rocket-chip/src/main/scala/util/package.scala:235:71]
  wire [8:0]       beats1 = io_mem_grant_bits_opcode[0] ? ~(_beats1_decode_T_1[11:3]) : 9'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:107:36, :222:14, :230:27, generators/rocket-chip/src/main/scala/util/package.scala:235:{46,71,76}]
  reg  [8:0]       counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27]
  wire [8:0]       _counter1_T = counter - 9'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :231:28]
  wire             refill_done = (counter == 9'h1 | beats1 == 9'h0) & io_mem_grant_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:222:14, :230:27, :233:{25,33,43}, :234:22]
  wire [8:0]       count = beats1 & ~_counter1_T;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:222:14, :231:28, :235:{25,27}]
  wire             _io_wb_req_valid_output = state == 4'h1;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:168:22, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire             _io_probe_rdy_T_2 = state == 4'h2;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:168:22, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire             _io_meta_write_bits_data_coh_T = state == 4'h3;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:168:22, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire             _io_mem_acquire_valid_T = state == 4'h4;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:168:22, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire             _sec_rdy_T_6 = state == 4'h5;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:168:22, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire             sec_rdy = idx_match & (_io_wb_req_valid_output | _io_probe_rdy_T_2 | _io_meta_write_bits_data_coh_T | (_io_mem_acquire_valid_T | _sec_rdy_T_6) & ~((_c_cat_T_123 | _c_cat_T_124 | _c_cat_T_126 | _c_cat_T_128 | _c_cat_T_129 | _c_cat_T_130 | _c_cat_T_131 | _c_cat_T_135 | _c_cat_T_136 | _c_cat_T_137 | _c_cat_T_138 | _c_cat_T_139 | _c_cat_T_146 | _c_cat_T_148) & ~(_needs_second_acq_T_27 | _needs_second_acq_T_28 | _needs_second_acq_T_30 | _needs_second_acq_T_32 | _needs_second_acq_T_33 | _needs_second_acq_T_34 | _needs_second_acq_T_35 | _needs_second_acq_T_39 | _needs_second_acq_T_40 | _needs_second_acq_T_41 | _needs_second_acq_T_42 | _needs_second_acq_T_43 | _needs_second_acq_T_50 | _needs_second_acq_T_52)) & ~refill_done);	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:86:{32,49,66}, :87:{54,64,71}, generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:174:27, :189:27, :190:56, :192:{23,52,55}, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:234:22, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:104:{54,57}, generators/rocket-chip/src/main/scala/util/package.scala:16:47, :73:59]
  wire             _rpq_io_enq_valid_T = io_req_pri_val & _io_req_pri_rdy_output;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:195:39, :197:75]
  wire             _io_replay_valid_T = state == 4'h8;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:168:22, :197:49, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  assign _io_req_pri_rdy_output = state == 4'h0;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:168:22, :197:75]
  reg              acked;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:199:18]
  wire             _io_meta_write_valid_T = state == 4'h6;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:168:22, :209:15]
  wire             can_finish = _io_req_pri_rdy_output | _io_mem_acquire_valid_T;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:197:75, generators/rocket-chip/src/main/scala/util/package.scala:16:47, :73:59]
  wire             _io_req_sec_rdy_output = sec_rdy & _rpq_io_enq_ready;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:189:27, :194:19, :270:29]
  reg  [1:0]       meta_hazard;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:272:28]
  wire             _io_meta_write_valid_output = _io_meta_write_valid_T | _io_meta_write_bits_data_coh_T;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:209:15, generators/rocket-chip/src/main/scala/util/package.scala:16:47, :73:59]
  wire             _io_mem_acquire_valid_output = _io_mem_acquire_valid_T & _grantackq_io_enq_ready;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:257:25, :292:50, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire [3:0]       _GEN_0 = {_c_cat_T_123 | _c_cat_T_124 | _c_cat_T_126 | _c_cat_T_128 | _c_cat_T_129 | _c_cat_T_130 | _c_cat_T_131 | _c_cat_T_135 | _c_cat_T_136 | _c_cat_T_137 | _c_cat_T_138 | _c_cat_T_139, _c_cat_T_123 | _c_cat_T_124 | _c_cat_T_126 | _c_cat_T_128 | _c_cat_T_129 | _c_cat_T_130 | _c_cat_T_131 | _c_cat_T_135 | _c_cat_T_136 | _c_cat_T_137 | _c_cat_T_138 | _c_cat_T_139 | _c_cat_T_146 | _c_cat_T_148, io_req_bits_old_meta_coh_state};	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:86:{32,49,66,76}, :87:{54,64,71}, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:58:19, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire [1:0]       _GEN_1 = {1'h0, _GEN_0 == 4'hC};	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:58:19, generators/rocket-chip/src/main/scala/util/Misc.scala:35:36, :49:20, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire             is_hit = _GEN_0 == 4'h3 | _GEN_0 == 4'h2 | _GEN_0 == 4'h1 | _GEN_0 == 4'h7 | _GEN_0 == 4'h6 | (&_GEN_0) | _GEN_0 == 4'hE;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:205:15, :209:15, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:58:19, generators/rocket-chip/src/main/scala/util/Misc.scala:35:9, :49:20, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire [15:0][1:0] _GEN_2 = {{2'h3}, {2'h3}, {2'h2}, {_GEN_1}, {_GEN_1}, {_GEN_1}, {_GEN_1}, {_GEN_1}, {2'h3}, {2'h2}, {2'h2}, {2'h1}, {2'h3}, {2'h2}, {2'h1}, {2'h0}};	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:35:36, :49:20]
  wire [3:0]       _coh_on_grant_T = {_needs_second_acq_T_27 | _needs_second_acq_T_28 | _needs_second_acq_T_30 | _needs_second_acq_T_32 | _needs_second_acq_T_33 | _needs_second_acq_T_34 | _needs_second_acq_T_35 | _needs_second_acq_T_39 | _needs_second_acq_T_40 | _needs_second_acq_T_41 | _needs_second_acq_T_42 | _needs_second_acq_T_43, _needs_second_acq_T_27 | _needs_second_acq_T_28 | _needs_second_acq_T_30 | _needs_second_acq_T_32 | _needs_second_acq_T_33 | _needs_second_acq_T_34 | _needs_second_acq_T_35 | _needs_second_acq_T_39 | _needs_second_acq_T_40 | _needs_second_acq_T_41 | _needs_second_acq_T_42 | _needs_second_acq_T_43 | _needs_second_acq_T_50 | _needs_second_acq_T_52, io_mem_grant_bits_param};	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:86:{32,49,66,76}, :87:{54,64,71}, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:84:18, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire [3:0]       _GEN_3 = {_needs_second_acq_T_27 | _needs_second_acq_T_28 | _needs_second_acq_T_30 | _needs_second_acq_T_32 | _needs_second_acq_T_33 | _needs_second_acq_T_34 | _needs_second_acq_T_35 | _needs_second_acq_T_39 | _needs_second_acq_T_40 | _needs_second_acq_T_41 | _needs_second_acq_T_42 | _needs_second_acq_T_43, _needs_second_acq_T_27 | _needs_second_acq_T_28 | _needs_second_acq_T_30 | _needs_second_acq_T_32 | _needs_second_acq_T_33 | _needs_second_acq_T_34 | _needs_second_acq_T_35 | _needs_second_acq_T_39 | _needs_second_acq_T_40 | _needs_second_acq_T_41 | _needs_second_acq_T_42 | _needs_second_acq_T_43 | _needs_second_acq_T_50 | _needs_second_acq_T_52, new_coh_state};	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:86:{32,49,66,76}, :87:{54,64,71}, generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:176:24, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:58:19, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire [3:0]       _GEN_4 = {_c_cat_T_123 | _c_cat_T_124 | _c_cat_T_126 | _c_cat_T_128 | _c_cat_T_129 | _c_cat_T_130 | _c_cat_T_131 | _c_cat_T_135 | _c_cat_T_136 | _c_cat_T_137 | _c_cat_T_138 | _c_cat_T_139, _c_cat_T_123 | _c_cat_T_124 | _c_cat_T_126 | _c_cat_T_128 | _c_cat_T_129 | _c_cat_T_130 | _c_cat_T_131 | _c_cat_T_135 | _c_cat_T_136 | _c_cat_T_137 | _c_cat_T_138 | _c_cat_T_139 | _c_cat_T_146 | _c_cat_T_148, new_coh_state};	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:86:{32,49,66,76}, :87:{54,64,71}, generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:176:24, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:58:19, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire             _GEN_5 = _sec_rdy_T_6 & refill_done;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:212:33, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:234:22, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire [1:0]       _GEN_6 = {1'h0, _GEN_4 == 4'hC};	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:58:19, generators/rocket-chip/src/main/scala/util/Misc.scala:35:36, :49:20, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire [15:0][1:0] _GEN_7 = {{2'h3}, {2'h3}, {2'h2}, {_GEN_6}, {_GEN_6}, {_GEN_6}, {_GEN_6}, {_GEN_6}, {2'h3}, {2'h2}, {2'h2}, {2'h1}, {2'h3}, {2'h2}, {2'h1}, {2'h0}};	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:35:36, :49:20]
  wire [1:0]       _GEN_8 = {1'h0, _GEN_3 == 4'hC};	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:58:19, generators/rocket-chip/src/main/scala/util/Misc.scala:35:36, :49:20, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire [15:0][1:0] _GEN_9 = {{2'h3}, {2'h3}, {2'h2}, {_GEN_8}, {_GEN_8}, {_GEN_8}, {_GEN_8}, {_GEN_8}, {2'h3}, {2'h2}, {2'h2}, {2'h1}, {2'h3}, {2'h2}, {2'h1}, {2'h0}};	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:35:36, :49:20]
  wire [1:0]       dirties_cat = {_c_cat_T_123 | _c_cat_T_124 | _c_cat_T_126 | _c_cat_T_128 | _c_cat_T_129 | _c_cat_T_130 | _c_cat_T_131 | _c_cat_T_135 | _c_cat_T_136 | _c_cat_T_137 | _c_cat_T_138 | _c_cat_T_139, _c_cat_T_123 | _c_cat_T_124 | _c_cat_T_126 | _c_cat_T_128 | _c_cat_T_129 | _c_cat_T_130 | _c_cat_T_131 | _c_cat_T_135 | _c_cat_T_136 | _c_cat_T_137 | _c_cat_T_138 | _c_cat_T_139 | _c_cat_T_146 | _c_cat_T_148};	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:86:{32,49,66,76}, :87:{54,64,71}, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:29:18, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire             _GEN_10 = io_req_sec_val & _io_req_sec_rdy_output;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:228:24, :270:29]
  always @(posedge clock) begin
    if (reset) begin
      state <= 4'h0;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:168:22]
      new_coh_state <= 2'h0;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:176:24]
      counter <= 9'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27]
      meta_hazard <= 2'h0;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:272:28]
    end
    else begin
      if (_rpq_io_enq_valid_T) begin	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:195:39]
        state <= io_req_bits_tag_match ? {2'h1, is_hit, 1'h0} : {2'h0, io_req_bits_old_meta_coh_state != 2'h3, 1'h1};	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:168:22, :170:16, :243:34, :244:21, :246:15, :249:15, :253:{13,19}, generators/rocket-chip/src/main/scala/util/Misc.scala:35:9, :38:9, :56:20]
        new_coh_state <= io_req_bits_tag_match ? (is_hit ? _GEN_2[_GEN_0] : io_req_bits_old_meta_coh_state) : 2'h0;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:176:24, :243:34, :244:21, :245:17, :248:17, :252:15, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:58:19, generators/rocket-chip/src/main/scala/util/Misc.scala:35:{9,36}, :49:20]
      end
      else begin	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:195:39]
        if (io_wb_req_ready & _io_wb_req_valid_output)	// @[generators/rocket-chip/src/main/scala/util/package.scala:16:47, src/main/scala/chisel3/util/Decoupled.scala:52:35]
          state <= 4'h2;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:168:22, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
        else if (_io_probe_rdy_T_2 & io_wb_req_ready & acked)	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:199:18, :222:48, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
          state <= 4'h3;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:168:22, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
        else if (_io_meta_write_bits_data_coh_T & io_meta_write_ready)	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:219:32, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
          state <= 4'h4;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:168:22, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
        else if (io_mem_acquire_ready & _io_mem_acquire_valid_output)	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:292:50, src/main/scala/chisel3/util/Decoupled.scala:52:35]
          state <= 4'h5;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:168:22, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
        else if (_GEN_5)	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:212:33]
          state <= 4'h6;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:168:22, :209:15]
        else if (_io_meta_write_valid_T & io_meta_write_ready)	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:209:{15,36}]
          state <= 4'h7;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:168:22, :205:15]
        else if (state == 4'h7)	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:168:22, :205:15]
          state <= 4'h8;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:168:22, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
        else if (_io_replay_valid_T & ~_rpq_io_deq_valid)	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:194:19, :197:49, :202:{31,34}]
          state <= 4'h0;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:168:22]
        if (_GEN_10 & (_GEN_3 == 4'h3 | _GEN_3 == 4'h2 | _GEN_3 == 4'h1 | _GEN_3 == 4'h7 | _GEN_3 == 4'h6 | (&_GEN_3) | _GEN_3 == 4'hE) & (_GEN_4 == 4'h3 | _GEN_4 == 4'h2 | _GEN_4 == 4'h1 | _GEN_4 == 4'h7 | _GEN_4 == 4'h6 | (&_GEN_4) | _GEN_4 == 4'hE)) begin	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:205:15, :209:15, :212:49, :228:{24,43}, :233:25, :234:15, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:58:19, generators/rocket-chip/src/main/scala/util/Misc.scala:35:9, :49:20, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
          if (&dirties_cat)	// @[generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:29:18, :106:42]
            new_coh_state <= _GEN_7[_GEN_4];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:176:24, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:58:19, generators/rocket-chip/src/main/scala/util/Misc.scala:35:36, :49:20]
          else	// @[generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:106:42]
            new_coh_state <= _GEN_9[_GEN_3];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:176:24, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:58:19, generators/rocket-chip/src/main/scala/util/Misc.scala:35:36, :49:20]
        end
        else if (_GEN_5)	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:212:33]
          new_coh_state <= _coh_on_grant_T == 4'hC ? 2'h3 : _coh_on_grant_T == 4'h4 | _coh_on_grant_T == 4'h0 ? 2'h2 : {1'h0, _coh_on_grant_T == 4'h1};	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:168:22, :170:16, :176:24, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:84:18, generators/rocket-chip/src/main/scala/util/package.scala:16:47, src/main/scala/chisel3/util/Mux.scala:77:13]
      end
      if (io_mem_grant_valid) begin	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:145:14]
        if (counter == 9'h0)	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :232:25]
          counter <= beats1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:222:14, :230:27]
        else	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:232:25]
          counter <= _counter1_T;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27, :231:28]
      end
      if (io_meta_write_ready & _io_meta_write_valid_output)	// @[generators/rocket-chip/src/main/scala/util/package.scala:73:59, src/main/scala/chisel3/util/Decoupled.scala:52:35]
        meta_hazard <= 2'h1;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:272:28]
      else if (|meta_hazard)	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:272:28, :273:21]
        meta_hazard <= meta_hazard + 2'h1;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:272:28, :273:59]
    end
    if (_rpq_io_enq_valid_T) begin	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:195:39]
      req_addr <= io_req_bits_addr;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16]
      req_old_meta_coh_state <= io_req_bits_old_meta_coh_state;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16]
      req_old_meta_tag <= io_req_bits_old_meta_tag;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16]
      req_way_en <= io_req_bits_way_en;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16]
    end
    if (_rpq_io_enq_valid_T | _GEN_10 & (&dirties_cat))	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, :195:39, :228:{24,43}, :232:13, :237:43, :238:9, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:29:18, :106:42, :109:27]
      req_cmd <= io_req_bits_cmd;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16]
    acked <= ~_rpq_io_enq_valid_T & (io_mem_grant_valid | acked);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:195:39, :199:18, :200:{29,37}, :237:43, :239:11]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:3];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM[i[1:0]] = `RANDOM;
        end
        state = _RANDOM[2'h0][3:0];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:168:22]
        req_addr = {_RANDOM[2'h0][31:4], _RANDOM[2'h1][11:0]};	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:168:22, :170:16]
        req_cmd = _RANDOM[2'h1][25:21];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16]
        req_old_meta_coh_state = _RANDOM[2'h2][10:9];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16]
        req_old_meta_tag = _RANDOM[2'h2][30:11];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16]
        req_way_en = {_RANDOM[2'h2][31], _RANDOM[2'h3][2:0]};	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16]
        new_coh_state = _RANDOM[2'h3][4:3];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, :176:24]
        counter = _RANDOM[2'h3][13:5];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:230:27]
        acked = _RANDOM[2'h3][14];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, :199:18]
        meta_hazard = _RANDOM[2'h3][16:15];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, :272:28]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Queue_105 rpq (	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:194:19]
    .clock                (clock),
    .reset                (reset),
    .io_enq_ready         (_rpq_io_enq_ready),
    .io_enq_valid         ((_rpq_io_enq_valid_T | io_req_sec_val & sec_rdy) & ~(io_req_bits_cmd == 5'h2 | _c_cat_T_146)),	// @[generators/rocket-chip/src/main/scala/rocket/Consts.scala:84:{35,45}, :87:54, generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:189:27, :195:{39,57,75,87,90}]
    .io_enq_bits_addr     (io_req_bits_addr),
    .io_enq_bits_tag      (io_req_bits_tag),
    .io_enq_bits_cmd      (io_req_bits_cmd),
    .io_enq_bits_size     (io_req_bits_size),
    .io_enq_bits_signed   (io_req_bits_signed),
    .io_enq_bits_dprv     (io_req_bits_dprv),
    .io_enq_bits_dv       (io_req_bits_dv),
    .io_enq_bits_phys     (io_req_bits_phys),
    .io_enq_bits_no_alloc (io_req_bits_no_alloc),
    .io_enq_bits_no_xcpt  (io_req_bits_no_xcpt),
    .io_enq_bits_sdq_id   (io_req_bits_sdq_id),
    .io_deq_ready         (io_meta_read_ready & (io_replay_ready & _io_replay_valid_T | _io_req_pri_rdy_output)),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:197:{20,40,49,66,75}, :309:30, :310:22]
    .io_deq_valid         (_rpq_io_deq_valid),
    .io_deq_bits_addr     (_rpq_io_deq_bits_addr),
    .io_deq_bits_tag      (io_replay_bits_tag),
    .io_deq_bits_cmd      (_rpq_io_deq_bits_cmd),
    .io_deq_bits_size     (io_replay_bits_size),
    .io_deq_bits_signed   (io_replay_bits_signed),
    .io_deq_bits_dprv     (io_replay_bits_dprv),
    .io_deq_bits_dv       (io_replay_bits_dv),
    .io_deq_bits_sdq_id   (io_replay_bits_sdq_id)
  );
  Queue_55 grantackq (	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:257:25]
    .clock            (clock),
    .reset            (reset),
    .io_enq_ready     (_grantackq_io_enq_ready),
    .io_enq_valid     (refill_done & io_mem_grant_bits_opcode[2] & ~(io_mem_grant_bits_opcode[1])),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:259:41, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:72:{36,43,52}, :234:22]
    .io_enq_bits_sink (io_mem_grant_bits_sink),
    .io_deq_ready     (io_mem_finish_ready & can_finish),	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:263:49, generators/rocket-chip/src/main/scala/util/package.scala:73:59]
    .io_deq_valid     (_grantackq_io_deq_valid),
    .io_deq_bits_sink (io_mem_finish_bits_sink)
  );
  assign io_req_pri_rdy = _io_req_pri_rdy_output;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:197:75]
  assign io_req_sec_rdy = _io_req_sec_rdy_output;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:270:29]
  assign io_idx_match = (|state) & idx_match;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:168:22, :174:27, :265:{26,41}]
  assign io_tag = req_addr[31:12];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, :172:26, :268:10]
  assign io_mem_acquire_valid = _io_mem_acquire_valid_output;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:292:50]
  assign io_mem_acquire_bits_param = {1'h0, _GEN[_grow_param_T]};	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:349:15, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:58:19, generators/rocket-chip/src/main/scala/util/Misc.scala:35:36, :49:20]
  assign io_mem_acquire_bits_address = {req_addr[31:6], 6'h0};	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, :173:51, :295:{48,66}]
  assign io_mem_finish_valid = _grantackq_io_deq_valid & can_finish;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:257:25, :261:49, generators/rocket-chip/src/main/scala/util/package.scala:73:59]
  assign io_refill_way_en = req_way_en;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16]
  assign io_refill_addr = {req_addr[11:6] | count[8:3], count[2:0], 3'h0};	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, :267:{18,36}, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:235:25]
  assign io_meta_read_valid = _io_replay_valid_T;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:197:49]
  assign io_meta_read_bits_idx = req_addr[11:6];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, :171:25]
  assign io_meta_write_valid = _io_meta_write_valid_output;	// @[generators/rocket-chip/src/main/scala/util/package.scala:73:59]
  assign io_meta_write_bits_idx = req_addr[11:6];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, :171:25]
  assign io_meta_write_bits_way_en = req_way_en;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16]
  assign io_meta_write_bits_data_coh_state = _io_meta_write_bits_data_coh_T ? 2'h0 : new_coh_state;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:176:24, :280:37, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  assign io_meta_write_bits_data_tag = req_addr[31:12];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, :172:26, :268:10]
  assign io_replay_valid = _io_replay_valid_T & _rpq_io_deq_valid;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:194:19, :197:49, :304:44]
  assign io_replay_bits_addr = {8'h0, req_addr[31:6], _rpq_io_deq_bits_addr[5:0]};	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, :194:19, :295:48, :307:{23,67}, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:233:25]
  assign io_replay_bits_cmd = io_meta_read_ready ? _rpq_io_deq_bits_cmd : 5'h5;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:194:19, :305:18, :309:30, :311:24]
  assign io_wb_req_valid = _io_wb_req_valid_output;	// @[generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  assign io_wb_req_bits_tag = req_old_meta_tag;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16]
  assign io_wb_req_bits_idx = req_addr[11:6];	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, :171:25]
  assign io_wb_req_bits_param = (&req_old_meta_coh_state) | req_old_meta_coh_state == 2'h2 ? 3'h1 : req_old_meta_coh_state == 2'h1 ? 3'h2 : req_old_meta_coh_state == 2'h0 ? 3'h5 : 3'h0;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16, generators/rocket-chip/src/main/scala/util/Misc.scala:38:36, :56:20]
  assign io_wb_req_bits_way_en = req_way_en;	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:170:16]
  assign io_probe_rdy = ~idx_match | ~(_io_wb_req_valid_output | _io_probe_rdy_T_2 | _io_meta_write_bits_data_coh_T) & ~(|meta_hazard);	// @[generators/rocket-chip/src/main/scala/rocket/NBDcache.scala:174:27, :272:28, :273:21, :275:{19,30,34,71,86}, generators/rocket-chip/src/main/scala/util/package.scala:16:47, :73:59]
endmodule

