// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module TilePRCIDomain_2(
  input          auto_intsink_in_sync_0,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]   auto_element_reset_domain_rockettile_hartid_in,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output         auto_element_reset_domain_rockettile_data_ready_out_nodes_2_out_2,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_element_reset_domain_rockettile_data_ready_out_nodes_2_out_1,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_element_reset_domain_rockettile_data_ready_out_nodes_2_out_0,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_element_reset_domain_rockettile_data_valid_in_nodes_2_in_2,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_element_reset_domain_rockettile_data_valid_in_nodes_2_in_1,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_element_reset_domain_rockettile_data_valid_in_nodes_2_in_0,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [159:0] auto_element_reset_domain_rockettile_data_bits_in_nodes_2_in_2,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_element_reset_domain_rockettile_data_bits_in_nodes_2_in_1,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_element_reset_domain_rockettile_data_bits_in_nodes_2_in_0,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output         auto_element_reset_domain_rockettile_rocc_ready_out_2_out,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_element_reset_domain_rockettile_rocc_valid_in_2_in,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [54:0]  auto_element_reset_domain_rockettile_rocc_bits_in_2_in,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_int_in_clock_xing_in_2_sync_0,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_int_in_clock_xing_in_1_sync_0,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_int_in_clock_xing_in_0_sync_0,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_int_in_clock_xing_in_0_sync_1,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]   auto_tl_master_clock_xing_out_a_mem_0_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tl_master_clock_xing_out_a_mem_0_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]   auto_tl_master_clock_xing_out_a_mem_0_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]   auto_tl_master_clock_xing_out_a_mem_0_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0]  auto_tl_master_clock_xing_out_a_mem_0_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [7:0]   auto_tl_master_clock_xing_out_a_mem_0_mask,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0]  auto_tl_master_clock_xing_out_a_mem_0_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]   auto_tl_master_clock_xing_out_a_mem_1_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tl_master_clock_xing_out_a_mem_1_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]   auto_tl_master_clock_xing_out_a_mem_1_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]   auto_tl_master_clock_xing_out_a_mem_1_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0]  auto_tl_master_clock_xing_out_a_mem_1_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [7:0]   auto_tl_master_clock_xing_out_a_mem_1_mask,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0]  auto_tl_master_clock_xing_out_a_mem_1_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]   auto_tl_master_clock_xing_out_a_mem_2_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tl_master_clock_xing_out_a_mem_2_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]   auto_tl_master_clock_xing_out_a_mem_2_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]   auto_tl_master_clock_xing_out_a_mem_2_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0]  auto_tl_master_clock_xing_out_a_mem_2_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [7:0]   auto_tl_master_clock_xing_out_a_mem_2_mask,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0]  auto_tl_master_clock_xing_out_a_mem_2_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]   auto_tl_master_clock_xing_out_a_mem_3_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tl_master_clock_xing_out_a_mem_3_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]   auto_tl_master_clock_xing_out_a_mem_3_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]   auto_tl_master_clock_xing_out_a_mem_3_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0]  auto_tl_master_clock_xing_out_a_mem_3_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [7:0]   auto_tl_master_clock_xing_out_a_mem_3_mask,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0]  auto_tl_master_clock_xing_out_a_mem_3_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]   auto_tl_master_clock_xing_out_a_mem_4_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tl_master_clock_xing_out_a_mem_4_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]   auto_tl_master_clock_xing_out_a_mem_4_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]   auto_tl_master_clock_xing_out_a_mem_4_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0]  auto_tl_master_clock_xing_out_a_mem_4_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [7:0]   auto_tl_master_clock_xing_out_a_mem_4_mask,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0]  auto_tl_master_clock_xing_out_a_mem_4_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]   auto_tl_master_clock_xing_out_a_mem_5_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tl_master_clock_xing_out_a_mem_5_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]   auto_tl_master_clock_xing_out_a_mem_5_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]   auto_tl_master_clock_xing_out_a_mem_5_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0]  auto_tl_master_clock_xing_out_a_mem_5_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [7:0]   auto_tl_master_clock_xing_out_a_mem_5_mask,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0]  auto_tl_master_clock_xing_out_a_mem_5_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]   auto_tl_master_clock_xing_out_a_mem_6_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tl_master_clock_xing_out_a_mem_6_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]   auto_tl_master_clock_xing_out_a_mem_6_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]   auto_tl_master_clock_xing_out_a_mem_6_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0]  auto_tl_master_clock_xing_out_a_mem_6_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [7:0]   auto_tl_master_clock_xing_out_a_mem_6_mask,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0]  auto_tl_master_clock_xing_out_a_mem_6_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]   auto_tl_master_clock_xing_out_a_mem_7_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tl_master_clock_xing_out_a_mem_7_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]   auto_tl_master_clock_xing_out_a_mem_7_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]   auto_tl_master_clock_xing_out_a_mem_7_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0]  auto_tl_master_clock_xing_out_a_mem_7_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [7:0]   auto_tl_master_clock_xing_out_a_mem_7_mask,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0]  auto_tl_master_clock_xing_out_a_mem_7_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]   auto_tl_master_clock_xing_out_a_ridx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]   auto_tl_master_clock_xing_out_a_widx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_tl_master_clock_xing_out_a_safe_ridx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output         auto_tl_master_clock_xing_out_a_safe_widx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tl_master_clock_xing_out_a_safe_source_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_tl_master_clock_xing_out_a_safe_sink_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]   auto_tl_master_clock_xing_out_b_mem_0_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]   auto_tl_master_clock_xing_out_b_mem_0_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0]  auto_tl_master_clock_xing_out_b_mem_0_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]   auto_tl_master_clock_xing_out_b_mem_1_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]   auto_tl_master_clock_xing_out_b_mem_1_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0]  auto_tl_master_clock_xing_out_b_mem_1_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]   auto_tl_master_clock_xing_out_b_mem_2_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]   auto_tl_master_clock_xing_out_b_mem_2_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0]  auto_tl_master_clock_xing_out_b_mem_2_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]   auto_tl_master_clock_xing_out_b_mem_3_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]   auto_tl_master_clock_xing_out_b_mem_3_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0]  auto_tl_master_clock_xing_out_b_mem_3_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]   auto_tl_master_clock_xing_out_b_mem_4_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]   auto_tl_master_clock_xing_out_b_mem_4_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0]  auto_tl_master_clock_xing_out_b_mem_4_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]   auto_tl_master_clock_xing_out_b_mem_5_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]   auto_tl_master_clock_xing_out_b_mem_5_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0]  auto_tl_master_clock_xing_out_b_mem_5_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]   auto_tl_master_clock_xing_out_b_mem_6_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]   auto_tl_master_clock_xing_out_b_mem_6_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0]  auto_tl_master_clock_xing_out_b_mem_6_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]   auto_tl_master_clock_xing_out_b_mem_7_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]   auto_tl_master_clock_xing_out_b_mem_7_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0]  auto_tl_master_clock_xing_out_b_mem_7_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]   auto_tl_master_clock_xing_out_b_ridx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]   auto_tl_master_clock_xing_out_b_widx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output         auto_tl_master_clock_xing_out_b_safe_ridx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_tl_master_clock_xing_out_b_safe_widx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tl_master_clock_xing_out_b_safe_source_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output         auto_tl_master_clock_xing_out_b_safe_sink_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]   auto_tl_master_clock_xing_out_c_mem_0_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tl_master_clock_xing_out_c_mem_0_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]   auto_tl_master_clock_xing_out_c_mem_0_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]   auto_tl_master_clock_xing_out_c_mem_0_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0]  auto_tl_master_clock_xing_out_c_mem_0_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0]  auto_tl_master_clock_xing_out_c_mem_0_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]   auto_tl_master_clock_xing_out_c_mem_1_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tl_master_clock_xing_out_c_mem_1_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]   auto_tl_master_clock_xing_out_c_mem_1_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]   auto_tl_master_clock_xing_out_c_mem_1_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0]  auto_tl_master_clock_xing_out_c_mem_1_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0]  auto_tl_master_clock_xing_out_c_mem_1_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]   auto_tl_master_clock_xing_out_c_mem_2_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tl_master_clock_xing_out_c_mem_2_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]   auto_tl_master_clock_xing_out_c_mem_2_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]   auto_tl_master_clock_xing_out_c_mem_2_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0]  auto_tl_master_clock_xing_out_c_mem_2_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0]  auto_tl_master_clock_xing_out_c_mem_2_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]   auto_tl_master_clock_xing_out_c_mem_3_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tl_master_clock_xing_out_c_mem_3_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]   auto_tl_master_clock_xing_out_c_mem_3_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]   auto_tl_master_clock_xing_out_c_mem_3_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0]  auto_tl_master_clock_xing_out_c_mem_3_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0]  auto_tl_master_clock_xing_out_c_mem_3_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]   auto_tl_master_clock_xing_out_c_mem_4_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tl_master_clock_xing_out_c_mem_4_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]   auto_tl_master_clock_xing_out_c_mem_4_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]   auto_tl_master_clock_xing_out_c_mem_4_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0]  auto_tl_master_clock_xing_out_c_mem_4_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0]  auto_tl_master_clock_xing_out_c_mem_4_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]   auto_tl_master_clock_xing_out_c_mem_5_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tl_master_clock_xing_out_c_mem_5_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]   auto_tl_master_clock_xing_out_c_mem_5_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]   auto_tl_master_clock_xing_out_c_mem_5_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0]  auto_tl_master_clock_xing_out_c_mem_5_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0]  auto_tl_master_clock_xing_out_c_mem_5_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]   auto_tl_master_clock_xing_out_c_mem_6_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tl_master_clock_xing_out_c_mem_6_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]   auto_tl_master_clock_xing_out_c_mem_6_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]   auto_tl_master_clock_xing_out_c_mem_6_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0]  auto_tl_master_clock_xing_out_c_mem_6_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0]  auto_tl_master_clock_xing_out_c_mem_6_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]   auto_tl_master_clock_xing_out_c_mem_7_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tl_master_clock_xing_out_c_mem_7_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]   auto_tl_master_clock_xing_out_c_mem_7_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]   auto_tl_master_clock_xing_out_c_mem_7_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0]  auto_tl_master_clock_xing_out_c_mem_7_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0]  auto_tl_master_clock_xing_out_c_mem_7_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]   auto_tl_master_clock_xing_out_c_ridx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]   auto_tl_master_clock_xing_out_c_widx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_tl_master_clock_xing_out_c_safe_ridx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output         auto_tl_master_clock_xing_out_c_safe_widx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tl_master_clock_xing_out_c_safe_source_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_tl_master_clock_xing_out_c_safe_sink_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]   auto_tl_master_clock_xing_out_d_mem_0_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]   auto_tl_master_clock_xing_out_d_mem_0_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]   auto_tl_master_clock_xing_out_d_mem_0_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]   auto_tl_master_clock_xing_out_d_mem_0_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]   auto_tl_master_clock_xing_out_d_mem_0_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_tl_master_clock_xing_out_d_mem_0_denied,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0]  auto_tl_master_clock_xing_out_d_mem_0_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_tl_master_clock_xing_out_d_mem_0_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]   auto_tl_master_clock_xing_out_d_mem_1_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]   auto_tl_master_clock_xing_out_d_mem_1_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]   auto_tl_master_clock_xing_out_d_mem_1_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]   auto_tl_master_clock_xing_out_d_mem_1_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]   auto_tl_master_clock_xing_out_d_mem_1_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_tl_master_clock_xing_out_d_mem_1_denied,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0]  auto_tl_master_clock_xing_out_d_mem_1_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_tl_master_clock_xing_out_d_mem_1_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]   auto_tl_master_clock_xing_out_d_mem_2_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]   auto_tl_master_clock_xing_out_d_mem_2_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]   auto_tl_master_clock_xing_out_d_mem_2_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]   auto_tl_master_clock_xing_out_d_mem_2_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]   auto_tl_master_clock_xing_out_d_mem_2_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_tl_master_clock_xing_out_d_mem_2_denied,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0]  auto_tl_master_clock_xing_out_d_mem_2_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_tl_master_clock_xing_out_d_mem_2_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]   auto_tl_master_clock_xing_out_d_mem_3_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]   auto_tl_master_clock_xing_out_d_mem_3_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]   auto_tl_master_clock_xing_out_d_mem_3_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]   auto_tl_master_clock_xing_out_d_mem_3_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]   auto_tl_master_clock_xing_out_d_mem_3_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_tl_master_clock_xing_out_d_mem_3_denied,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0]  auto_tl_master_clock_xing_out_d_mem_3_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_tl_master_clock_xing_out_d_mem_3_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]   auto_tl_master_clock_xing_out_d_mem_4_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]   auto_tl_master_clock_xing_out_d_mem_4_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]   auto_tl_master_clock_xing_out_d_mem_4_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]   auto_tl_master_clock_xing_out_d_mem_4_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]   auto_tl_master_clock_xing_out_d_mem_4_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_tl_master_clock_xing_out_d_mem_4_denied,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0]  auto_tl_master_clock_xing_out_d_mem_4_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_tl_master_clock_xing_out_d_mem_4_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]   auto_tl_master_clock_xing_out_d_mem_5_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]   auto_tl_master_clock_xing_out_d_mem_5_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]   auto_tl_master_clock_xing_out_d_mem_5_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]   auto_tl_master_clock_xing_out_d_mem_5_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]   auto_tl_master_clock_xing_out_d_mem_5_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_tl_master_clock_xing_out_d_mem_5_denied,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0]  auto_tl_master_clock_xing_out_d_mem_5_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_tl_master_clock_xing_out_d_mem_5_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]   auto_tl_master_clock_xing_out_d_mem_6_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]   auto_tl_master_clock_xing_out_d_mem_6_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]   auto_tl_master_clock_xing_out_d_mem_6_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]   auto_tl_master_clock_xing_out_d_mem_6_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]   auto_tl_master_clock_xing_out_d_mem_6_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_tl_master_clock_xing_out_d_mem_6_denied,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0]  auto_tl_master_clock_xing_out_d_mem_6_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_tl_master_clock_xing_out_d_mem_6_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]   auto_tl_master_clock_xing_out_d_mem_7_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]   auto_tl_master_clock_xing_out_d_mem_7_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]   auto_tl_master_clock_xing_out_d_mem_7_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]   auto_tl_master_clock_xing_out_d_mem_7_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]   auto_tl_master_clock_xing_out_d_mem_7_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_tl_master_clock_xing_out_d_mem_7_denied,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0]  auto_tl_master_clock_xing_out_d_mem_7_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_tl_master_clock_xing_out_d_mem_7_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]   auto_tl_master_clock_xing_out_d_ridx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]   auto_tl_master_clock_xing_out_d_widx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output         auto_tl_master_clock_xing_out_d_safe_ridx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_tl_master_clock_xing_out_d_safe_widx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tl_master_clock_xing_out_d_safe_source_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output         auto_tl_master_clock_xing_out_d_safe_sink_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]   auto_tl_master_clock_xing_out_e_mem_0_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tl_master_clock_xing_out_e_mem_1_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tl_master_clock_xing_out_e_mem_2_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tl_master_clock_xing_out_e_mem_3_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tl_master_clock_xing_out_e_mem_4_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tl_master_clock_xing_out_e_mem_5_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tl_master_clock_xing_out_e_mem_6_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tl_master_clock_xing_out_e_mem_7_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]   auto_tl_master_clock_xing_out_e_ridx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]   auto_tl_master_clock_xing_out_e_widx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_tl_master_clock_xing_out_e_safe_ridx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output         auto_tl_master_clock_xing_out_e_safe_widx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tl_master_clock_xing_out_e_safe_source_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input          auto_tl_master_clock_xing_out_e_safe_sink_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tap_clock_in_clock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                 auto_tap_clock_in_reset	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
);

  wire        _intsink_3_auto_out_0;	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:80:29]
  wire        _intsink_2_auto_out_0;	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:80:29]
  wire        _intsink_1_auto_out_0;	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:80:29]
  wire        _intsink_1_auto_out_1;	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:80:29]
  wire        _intsink_auto_out_0;	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:80:29]
  wire        _asource_auto_in_a_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
  wire        _asource_auto_in_b_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
  wire [2:0]  _asource_auto_in_b_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
  wire [1:0]  _asource_auto_in_b_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
  wire [3:0]  _asource_auto_in_b_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
  wire [5:0]  _asource_auto_in_b_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
  wire [31:0] _asource_auto_in_b_bits_address;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
  wire [7:0]  _asource_auto_in_b_bits_mask;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
  wire        _asource_auto_in_b_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
  wire        _asource_auto_in_c_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
  wire        _asource_auto_in_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
  wire [2:0]  _asource_auto_in_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
  wire [1:0]  _asource_auto_in_d_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
  wire [3:0]  _asource_auto_in_d_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
  wire [5:0]  _asource_auto_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
  wire [2:0]  _asource_auto_in_d_bits_sink;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
  wire        _asource_auto_in_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
  wire [63:0] _asource_auto_in_d_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
  wire        _asource_auto_in_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
  wire        _asource_auto_in_e_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
  wire        _element_reset_domain_rockettile_auto_buffer_out_a_valid;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
  wire [2:0]  _element_reset_domain_rockettile_auto_buffer_out_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
  wire [2:0]  _element_reset_domain_rockettile_auto_buffer_out_a_bits_param;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
  wire [3:0]  _element_reset_domain_rockettile_auto_buffer_out_a_bits_size;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
  wire [5:0]  _element_reset_domain_rockettile_auto_buffer_out_a_bits_source;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
  wire [31:0] _element_reset_domain_rockettile_auto_buffer_out_a_bits_address;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
  wire [7:0]  _element_reset_domain_rockettile_auto_buffer_out_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
  wire [63:0] _element_reset_domain_rockettile_auto_buffer_out_a_bits_data;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
  wire        _element_reset_domain_rockettile_auto_buffer_out_b_ready;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
  wire        _element_reset_domain_rockettile_auto_buffer_out_c_valid;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
  wire [2:0]  _element_reset_domain_rockettile_auto_buffer_out_c_bits_opcode;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
  wire [2:0]  _element_reset_domain_rockettile_auto_buffer_out_c_bits_param;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
  wire [3:0]  _element_reset_domain_rockettile_auto_buffer_out_c_bits_size;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
  wire [5:0]  _element_reset_domain_rockettile_auto_buffer_out_c_bits_source;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
  wire [31:0] _element_reset_domain_rockettile_auto_buffer_out_c_bits_address;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
  wire [63:0] _element_reset_domain_rockettile_auto_buffer_out_c_bits_data;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
  wire        _element_reset_domain_rockettile_auto_buffer_out_d_ready;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
  wire        _element_reset_domain_rockettile_auto_buffer_out_e_valid;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
  wire [2:0]  _element_reset_domain_rockettile_auto_buffer_out_e_bits_sink;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
  wire        _element_reset_domain_rockettile_auto_wfi_out_0;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
  RocketTile_2 element_reset_domain_rockettile (	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
    .clock                             (auto_tap_clock_in_clock),
    .reset                             (auto_tap_clock_in_reset),
    .auto_buffer_out_a_ready           (_asource_auto_in_a_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
    .auto_buffer_out_a_valid           (_element_reset_domain_rockettile_auto_buffer_out_a_valid),
    .auto_buffer_out_a_bits_opcode     (_element_reset_domain_rockettile_auto_buffer_out_a_bits_opcode),
    .auto_buffer_out_a_bits_param      (_element_reset_domain_rockettile_auto_buffer_out_a_bits_param),
    .auto_buffer_out_a_bits_size       (_element_reset_domain_rockettile_auto_buffer_out_a_bits_size),
    .auto_buffer_out_a_bits_source     (_element_reset_domain_rockettile_auto_buffer_out_a_bits_source),
    .auto_buffer_out_a_bits_address    (_element_reset_domain_rockettile_auto_buffer_out_a_bits_address),
    .auto_buffer_out_a_bits_mask       (_element_reset_domain_rockettile_auto_buffer_out_a_bits_mask),
    .auto_buffer_out_a_bits_data       (_element_reset_domain_rockettile_auto_buffer_out_a_bits_data),
    .auto_buffer_out_b_ready           (_element_reset_domain_rockettile_auto_buffer_out_b_ready),
    .auto_buffer_out_b_valid           (_asource_auto_in_b_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
    .auto_buffer_out_b_bits_opcode     (_asource_auto_in_b_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
    .auto_buffer_out_b_bits_param      (_asource_auto_in_b_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
    .auto_buffer_out_b_bits_size       (_asource_auto_in_b_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
    .auto_buffer_out_b_bits_source     (_asource_auto_in_b_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
    .auto_buffer_out_b_bits_address    (_asource_auto_in_b_bits_address),	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
    .auto_buffer_out_b_bits_mask       (_asource_auto_in_b_bits_mask),	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
    .auto_buffer_out_b_bits_corrupt    (_asource_auto_in_b_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
    .auto_buffer_out_c_ready           (_asource_auto_in_c_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
    .auto_buffer_out_c_valid           (_element_reset_domain_rockettile_auto_buffer_out_c_valid),
    .auto_buffer_out_c_bits_opcode     (_element_reset_domain_rockettile_auto_buffer_out_c_bits_opcode),
    .auto_buffer_out_c_bits_param      (_element_reset_domain_rockettile_auto_buffer_out_c_bits_param),
    .auto_buffer_out_c_bits_size       (_element_reset_domain_rockettile_auto_buffer_out_c_bits_size),
    .auto_buffer_out_c_bits_source     (_element_reset_domain_rockettile_auto_buffer_out_c_bits_source),
    .auto_buffer_out_c_bits_address    (_element_reset_domain_rockettile_auto_buffer_out_c_bits_address),
    .auto_buffer_out_c_bits_data       (_element_reset_domain_rockettile_auto_buffer_out_c_bits_data),
    .auto_buffer_out_d_ready           (_element_reset_domain_rockettile_auto_buffer_out_d_ready),
    .auto_buffer_out_d_valid           (_asource_auto_in_d_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
    .auto_buffer_out_d_bits_opcode     (_asource_auto_in_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
    .auto_buffer_out_d_bits_param      (_asource_auto_in_d_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
    .auto_buffer_out_d_bits_size       (_asource_auto_in_d_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
    .auto_buffer_out_d_bits_source     (_asource_auto_in_d_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
    .auto_buffer_out_d_bits_sink       (_asource_auto_in_d_bits_sink),	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
    .auto_buffer_out_d_bits_denied     (_asource_auto_in_d_bits_denied),	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
    .auto_buffer_out_d_bits_data       (_asource_auto_in_d_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
    .auto_buffer_out_d_bits_corrupt    (_asource_auto_in_d_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
    .auto_buffer_out_e_ready           (_asource_auto_in_e_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
    .auto_buffer_out_e_valid           (_element_reset_domain_rockettile_auto_buffer_out_e_valid),
    .auto_buffer_out_e_bits_sink       (_element_reset_domain_rockettile_auto_buffer_out_e_bits_sink),
    .auto_wfi_out_0                    (_element_reset_domain_rockettile_auto_wfi_out_0),
    .auto_int_local_in_3_0             (_intsink_3_auto_out_0),	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:80:29]
    .auto_int_local_in_2_0             (_intsink_2_auto_out_0),	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:80:29]
    .auto_int_local_in_1_0             (_intsink_1_auto_out_0),	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:80:29]
    .auto_int_local_in_1_1             (_intsink_1_auto_out_1),	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:80:29]
    .auto_int_local_in_0_0             (_intsink_auto_out_0),	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:80:29]
    .auto_hartid_in                    (auto_element_reset_domain_rockettile_hartid_in),
    .auto_data_ready_out_nodes_2_out_2 (auto_element_reset_domain_rockettile_data_ready_out_nodes_2_out_2),
    .auto_data_ready_out_nodes_2_out_1 (auto_element_reset_domain_rockettile_data_ready_out_nodes_2_out_1),
    .auto_data_ready_out_nodes_2_out_0 (auto_element_reset_domain_rockettile_data_ready_out_nodes_2_out_0),
    .auto_data_valid_in_nodes_2_in_2   (auto_element_reset_domain_rockettile_data_valid_in_nodes_2_in_2),
    .auto_data_valid_in_nodes_2_in_1   (auto_element_reset_domain_rockettile_data_valid_in_nodes_2_in_1),
    .auto_data_valid_in_nodes_2_in_0   (auto_element_reset_domain_rockettile_data_valid_in_nodes_2_in_0),
    .auto_data_bits_in_nodes_2_in_2    (auto_element_reset_domain_rockettile_data_bits_in_nodes_2_in_2),
    .auto_data_bits_in_nodes_2_in_1    (auto_element_reset_domain_rockettile_data_bits_in_nodes_2_in_1),
    .auto_data_bits_in_nodes_2_in_0    (auto_element_reset_domain_rockettile_data_bits_in_nodes_2_in_0),
    .auto_rocc_ready_out_2_out         (auto_element_reset_domain_rockettile_rocc_ready_out_2_out),
    .auto_rocc_valid_in_2_in           (auto_element_reset_domain_rockettile_rocc_valid_in_2_in),
    .auto_rocc_bits_in_2_in            (auto_element_reset_domain_rockettile_rocc_bits_in_2_in)
  );
  TLAsyncCrossingSource_3 asource (	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
    .clock                          (auto_tap_clock_in_clock),
    .reset                          (auto_tap_clock_in_reset),
    .auto_in_a_ready                (_asource_auto_in_a_ready),
    .auto_in_a_valid                (_element_reset_domain_rockettile_auto_buffer_out_a_valid),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
    .auto_in_a_bits_opcode          (_element_reset_domain_rockettile_auto_buffer_out_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
    .auto_in_a_bits_param           (_element_reset_domain_rockettile_auto_buffer_out_a_bits_param),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
    .auto_in_a_bits_size            (_element_reset_domain_rockettile_auto_buffer_out_a_bits_size),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
    .auto_in_a_bits_source          (_element_reset_domain_rockettile_auto_buffer_out_a_bits_source),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
    .auto_in_a_bits_address         (_element_reset_domain_rockettile_auto_buffer_out_a_bits_address),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
    .auto_in_a_bits_mask            (_element_reset_domain_rockettile_auto_buffer_out_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
    .auto_in_a_bits_data            (_element_reset_domain_rockettile_auto_buffer_out_a_bits_data),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
    .auto_in_b_ready                (_element_reset_domain_rockettile_auto_buffer_out_b_ready),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
    .auto_in_b_valid                (_asource_auto_in_b_valid),
    .auto_in_b_bits_opcode          (_asource_auto_in_b_bits_opcode),
    .auto_in_b_bits_param           (_asource_auto_in_b_bits_param),
    .auto_in_b_bits_size            (_asource_auto_in_b_bits_size),
    .auto_in_b_bits_source          (_asource_auto_in_b_bits_source),
    .auto_in_b_bits_address         (_asource_auto_in_b_bits_address),
    .auto_in_b_bits_mask            (_asource_auto_in_b_bits_mask),
    .auto_in_b_bits_corrupt         (_asource_auto_in_b_bits_corrupt),
    .auto_in_c_ready                (_asource_auto_in_c_ready),
    .auto_in_c_valid                (_element_reset_domain_rockettile_auto_buffer_out_c_valid),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
    .auto_in_c_bits_opcode          (_element_reset_domain_rockettile_auto_buffer_out_c_bits_opcode),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
    .auto_in_c_bits_param           (_element_reset_domain_rockettile_auto_buffer_out_c_bits_param),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
    .auto_in_c_bits_size            (_element_reset_domain_rockettile_auto_buffer_out_c_bits_size),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
    .auto_in_c_bits_source          (_element_reset_domain_rockettile_auto_buffer_out_c_bits_source),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
    .auto_in_c_bits_address         (_element_reset_domain_rockettile_auto_buffer_out_c_bits_address),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
    .auto_in_c_bits_data            (_element_reset_domain_rockettile_auto_buffer_out_c_bits_data),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
    .auto_in_d_ready                (_element_reset_domain_rockettile_auto_buffer_out_d_ready),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
    .auto_in_d_valid                (_asource_auto_in_d_valid),
    .auto_in_d_bits_opcode          (_asource_auto_in_d_bits_opcode),
    .auto_in_d_bits_param           (_asource_auto_in_d_bits_param),
    .auto_in_d_bits_size            (_asource_auto_in_d_bits_size),
    .auto_in_d_bits_source          (_asource_auto_in_d_bits_source),
    .auto_in_d_bits_sink            (_asource_auto_in_d_bits_sink),
    .auto_in_d_bits_denied          (_asource_auto_in_d_bits_denied),
    .auto_in_d_bits_data            (_asource_auto_in_d_bits_data),
    .auto_in_d_bits_corrupt         (_asource_auto_in_d_bits_corrupt),
    .auto_in_e_ready                (_asource_auto_in_e_ready),
    .auto_in_e_valid                (_element_reset_domain_rockettile_auto_buffer_out_e_valid),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
    .auto_in_e_bits_sink            (_element_reset_domain_rockettile_auto_buffer_out_e_bits_sink),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
    .auto_out_a_mem_0_opcode        (auto_tl_master_clock_xing_out_a_mem_0_opcode),
    .auto_out_a_mem_0_param         (auto_tl_master_clock_xing_out_a_mem_0_param),
    .auto_out_a_mem_0_size          (auto_tl_master_clock_xing_out_a_mem_0_size),
    .auto_out_a_mem_0_source        (auto_tl_master_clock_xing_out_a_mem_0_source),
    .auto_out_a_mem_0_address       (auto_tl_master_clock_xing_out_a_mem_0_address),
    .auto_out_a_mem_0_mask          (auto_tl_master_clock_xing_out_a_mem_0_mask),
    .auto_out_a_mem_0_data          (auto_tl_master_clock_xing_out_a_mem_0_data),
    .auto_out_a_mem_1_opcode        (auto_tl_master_clock_xing_out_a_mem_1_opcode),
    .auto_out_a_mem_1_param         (auto_tl_master_clock_xing_out_a_mem_1_param),
    .auto_out_a_mem_1_size          (auto_tl_master_clock_xing_out_a_mem_1_size),
    .auto_out_a_mem_1_source        (auto_tl_master_clock_xing_out_a_mem_1_source),
    .auto_out_a_mem_1_address       (auto_tl_master_clock_xing_out_a_mem_1_address),
    .auto_out_a_mem_1_mask          (auto_tl_master_clock_xing_out_a_mem_1_mask),
    .auto_out_a_mem_1_data          (auto_tl_master_clock_xing_out_a_mem_1_data),
    .auto_out_a_mem_2_opcode        (auto_tl_master_clock_xing_out_a_mem_2_opcode),
    .auto_out_a_mem_2_param         (auto_tl_master_clock_xing_out_a_mem_2_param),
    .auto_out_a_mem_2_size          (auto_tl_master_clock_xing_out_a_mem_2_size),
    .auto_out_a_mem_2_source        (auto_tl_master_clock_xing_out_a_mem_2_source),
    .auto_out_a_mem_2_address       (auto_tl_master_clock_xing_out_a_mem_2_address),
    .auto_out_a_mem_2_mask          (auto_tl_master_clock_xing_out_a_mem_2_mask),
    .auto_out_a_mem_2_data          (auto_tl_master_clock_xing_out_a_mem_2_data),
    .auto_out_a_mem_3_opcode        (auto_tl_master_clock_xing_out_a_mem_3_opcode),
    .auto_out_a_mem_3_param         (auto_tl_master_clock_xing_out_a_mem_3_param),
    .auto_out_a_mem_3_size          (auto_tl_master_clock_xing_out_a_mem_3_size),
    .auto_out_a_mem_3_source        (auto_tl_master_clock_xing_out_a_mem_3_source),
    .auto_out_a_mem_3_address       (auto_tl_master_clock_xing_out_a_mem_3_address),
    .auto_out_a_mem_3_mask          (auto_tl_master_clock_xing_out_a_mem_3_mask),
    .auto_out_a_mem_3_data          (auto_tl_master_clock_xing_out_a_mem_3_data),
    .auto_out_a_mem_4_opcode        (auto_tl_master_clock_xing_out_a_mem_4_opcode),
    .auto_out_a_mem_4_param         (auto_tl_master_clock_xing_out_a_mem_4_param),
    .auto_out_a_mem_4_size          (auto_tl_master_clock_xing_out_a_mem_4_size),
    .auto_out_a_mem_4_source        (auto_tl_master_clock_xing_out_a_mem_4_source),
    .auto_out_a_mem_4_address       (auto_tl_master_clock_xing_out_a_mem_4_address),
    .auto_out_a_mem_4_mask          (auto_tl_master_clock_xing_out_a_mem_4_mask),
    .auto_out_a_mem_4_data          (auto_tl_master_clock_xing_out_a_mem_4_data),
    .auto_out_a_mem_5_opcode        (auto_tl_master_clock_xing_out_a_mem_5_opcode),
    .auto_out_a_mem_5_param         (auto_tl_master_clock_xing_out_a_mem_5_param),
    .auto_out_a_mem_5_size          (auto_tl_master_clock_xing_out_a_mem_5_size),
    .auto_out_a_mem_5_source        (auto_tl_master_clock_xing_out_a_mem_5_source),
    .auto_out_a_mem_5_address       (auto_tl_master_clock_xing_out_a_mem_5_address),
    .auto_out_a_mem_5_mask          (auto_tl_master_clock_xing_out_a_mem_5_mask),
    .auto_out_a_mem_5_data          (auto_tl_master_clock_xing_out_a_mem_5_data),
    .auto_out_a_mem_6_opcode        (auto_tl_master_clock_xing_out_a_mem_6_opcode),
    .auto_out_a_mem_6_param         (auto_tl_master_clock_xing_out_a_mem_6_param),
    .auto_out_a_mem_6_size          (auto_tl_master_clock_xing_out_a_mem_6_size),
    .auto_out_a_mem_6_source        (auto_tl_master_clock_xing_out_a_mem_6_source),
    .auto_out_a_mem_6_address       (auto_tl_master_clock_xing_out_a_mem_6_address),
    .auto_out_a_mem_6_mask          (auto_tl_master_clock_xing_out_a_mem_6_mask),
    .auto_out_a_mem_6_data          (auto_tl_master_clock_xing_out_a_mem_6_data),
    .auto_out_a_mem_7_opcode        (auto_tl_master_clock_xing_out_a_mem_7_opcode),
    .auto_out_a_mem_7_param         (auto_tl_master_clock_xing_out_a_mem_7_param),
    .auto_out_a_mem_7_size          (auto_tl_master_clock_xing_out_a_mem_7_size),
    .auto_out_a_mem_7_source        (auto_tl_master_clock_xing_out_a_mem_7_source),
    .auto_out_a_mem_7_address       (auto_tl_master_clock_xing_out_a_mem_7_address),
    .auto_out_a_mem_7_mask          (auto_tl_master_clock_xing_out_a_mem_7_mask),
    .auto_out_a_mem_7_data          (auto_tl_master_clock_xing_out_a_mem_7_data),
    .auto_out_a_ridx                (auto_tl_master_clock_xing_out_a_ridx),
    .auto_out_a_widx                (auto_tl_master_clock_xing_out_a_widx),
    .auto_out_a_safe_ridx_valid     (auto_tl_master_clock_xing_out_a_safe_ridx_valid),
    .auto_out_a_safe_widx_valid     (auto_tl_master_clock_xing_out_a_safe_widx_valid),
    .auto_out_a_safe_source_reset_n (auto_tl_master_clock_xing_out_a_safe_source_reset_n),
    .auto_out_a_safe_sink_reset_n   (auto_tl_master_clock_xing_out_a_safe_sink_reset_n),
    .auto_out_b_mem_0_param         (auto_tl_master_clock_xing_out_b_mem_0_param),
    .auto_out_b_mem_0_source        (auto_tl_master_clock_xing_out_b_mem_0_source),
    .auto_out_b_mem_0_address       (auto_tl_master_clock_xing_out_b_mem_0_address),
    .auto_out_b_mem_1_param         (auto_tl_master_clock_xing_out_b_mem_1_param),
    .auto_out_b_mem_1_source        (auto_tl_master_clock_xing_out_b_mem_1_source),
    .auto_out_b_mem_1_address       (auto_tl_master_clock_xing_out_b_mem_1_address),
    .auto_out_b_mem_2_param         (auto_tl_master_clock_xing_out_b_mem_2_param),
    .auto_out_b_mem_2_source        (auto_tl_master_clock_xing_out_b_mem_2_source),
    .auto_out_b_mem_2_address       (auto_tl_master_clock_xing_out_b_mem_2_address),
    .auto_out_b_mem_3_param         (auto_tl_master_clock_xing_out_b_mem_3_param),
    .auto_out_b_mem_3_source        (auto_tl_master_clock_xing_out_b_mem_3_source),
    .auto_out_b_mem_3_address       (auto_tl_master_clock_xing_out_b_mem_3_address),
    .auto_out_b_mem_4_param         (auto_tl_master_clock_xing_out_b_mem_4_param),
    .auto_out_b_mem_4_source        (auto_tl_master_clock_xing_out_b_mem_4_source),
    .auto_out_b_mem_4_address       (auto_tl_master_clock_xing_out_b_mem_4_address),
    .auto_out_b_mem_5_param         (auto_tl_master_clock_xing_out_b_mem_5_param),
    .auto_out_b_mem_5_source        (auto_tl_master_clock_xing_out_b_mem_5_source),
    .auto_out_b_mem_5_address       (auto_tl_master_clock_xing_out_b_mem_5_address),
    .auto_out_b_mem_6_param         (auto_tl_master_clock_xing_out_b_mem_6_param),
    .auto_out_b_mem_6_source        (auto_tl_master_clock_xing_out_b_mem_6_source),
    .auto_out_b_mem_6_address       (auto_tl_master_clock_xing_out_b_mem_6_address),
    .auto_out_b_mem_7_param         (auto_tl_master_clock_xing_out_b_mem_7_param),
    .auto_out_b_mem_7_source        (auto_tl_master_clock_xing_out_b_mem_7_source),
    .auto_out_b_mem_7_address       (auto_tl_master_clock_xing_out_b_mem_7_address),
    .auto_out_b_ridx                (auto_tl_master_clock_xing_out_b_ridx),
    .auto_out_b_widx                (auto_tl_master_clock_xing_out_b_widx),
    .auto_out_b_safe_ridx_valid     (auto_tl_master_clock_xing_out_b_safe_ridx_valid),
    .auto_out_b_safe_widx_valid     (auto_tl_master_clock_xing_out_b_safe_widx_valid),
    .auto_out_b_safe_source_reset_n (auto_tl_master_clock_xing_out_b_safe_source_reset_n),
    .auto_out_b_safe_sink_reset_n   (auto_tl_master_clock_xing_out_b_safe_sink_reset_n),
    .auto_out_c_mem_0_opcode        (auto_tl_master_clock_xing_out_c_mem_0_opcode),
    .auto_out_c_mem_0_param         (auto_tl_master_clock_xing_out_c_mem_0_param),
    .auto_out_c_mem_0_size          (auto_tl_master_clock_xing_out_c_mem_0_size),
    .auto_out_c_mem_0_source        (auto_tl_master_clock_xing_out_c_mem_0_source),
    .auto_out_c_mem_0_address       (auto_tl_master_clock_xing_out_c_mem_0_address),
    .auto_out_c_mem_0_data          (auto_tl_master_clock_xing_out_c_mem_0_data),
    .auto_out_c_mem_1_opcode        (auto_tl_master_clock_xing_out_c_mem_1_opcode),
    .auto_out_c_mem_1_param         (auto_tl_master_clock_xing_out_c_mem_1_param),
    .auto_out_c_mem_1_size          (auto_tl_master_clock_xing_out_c_mem_1_size),
    .auto_out_c_mem_1_source        (auto_tl_master_clock_xing_out_c_mem_1_source),
    .auto_out_c_mem_1_address       (auto_tl_master_clock_xing_out_c_mem_1_address),
    .auto_out_c_mem_1_data          (auto_tl_master_clock_xing_out_c_mem_1_data),
    .auto_out_c_mem_2_opcode        (auto_tl_master_clock_xing_out_c_mem_2_opcode),
    .auto_out_c_mem_2_param         (auto_tl_master_clock_xing_out_c_mem_2_param),
    .auto_out_c_mem_2_size          (auto_tl_master_clock_xing_out_c_mem_2_size),
    .auto_out_c_mem_2_source        (auto_tl_master_clock_xing_out_c_mem_2_source),
    .auto_out_c_mem_2_address       (auto_tl_master_clock_xing_out_c_mem_2_address),
    .auto_out_c_mem_2_data          (auto_tl_master_clock_xing_out_c_mem_2_data),
    .auto_out_c_mem_3_opcode        (auto_tl_master_clock_xing_out_c_mem_3_opcode),
    .auto_out_c_mem_3_param         (auto_tl_master_clock_xing_out_c_mem_3_param),
    .auto_out_c_mem_3_size          (auto_tl_master_clock_xing_out_c_mem_3_size),
    .auto_out_c_mem_3_source        (auto_tl_master_clock_xing_out_c_mem_3_source),
    .auto_out_c_mem_3_address       (auto_tl_master_clock_xing_out_c_mem_3_address),
    .auto_out_c_mem_3_data          (auto_tl_master_clock_xing_out_c_mem_3_data),
    .auto_out_c_mem_4_opcode        (auto_tl_master_clock_xing_out_c_mem_4_opcode),
    .auto_out_c_mem_4_param         (auto_tl_master_clock_xing_out_c_mem_4_param),
    .auto_out_c_mem_4_size          (auto_tl_master_clock_xing_out_c_mem_4_size),
    .auto_out_c_mem_4_source        (auto_tl_master_clock_xing_out_c_mem_4_source),
    .auto_out_c_mem_4_address       (auto_tl_master_clock_xing_out_c_mem_4_address),
    .auto_out_c_mem_4_data          (auto_tl_master_clock_xing_out_c_mem_4_data),
    .auto_out_c_mem_5_opcode        (auto_tl_master_clock_xing_out_c_mem_5_opcode),
    .auto_out_c_mem_5_param         (auto_tl_master_clock_xing_out_c_mem_5_param),
    .auto_out_c_mem_5_size          (auto_tl_master_clock_xing_out_c_mem_5_size),
    .auto_out_c_mem_5_source        (auto_tl_master_clock_xing_out_c_mem_5_source),
    .auto_out_c_mem_5_address       (auto_tl_master_clock_xing_out_c_mem_5_address),
    .auto_out_c_mem_5_data          (auto_tl_master_clock_xing_out_c_mem_5_data),
    .auto_out_c_mem_6_opcode        (auto_tl_master_clock_xing_out_c_mem_6_opcode),
    .auto_out_c_mem_6_param         (auto_tl_master_clock_xing_out_c_mem_6_param),
    .auto_out_c_mem_6_size          (auto_tl_master_clock_xing_out_c_mem_6_size),
    .auto_out_c_mem_6_source        (auto_tl_master_clock_xing_out_c_mem_6_source),
    .auto_out_c_mem_6_address       (auto_tl_master_clock_xing_out_c_mem_6_address),
    .auto_out_c_mem_6_data          (auto_tl_master_clock_xing_out_c_mem_6_data),
    .auto_out_c_mem_7_opcode        (auto_tl_master_clock_xing_out_c_mem_7_opcode),
    .auto_out_c_mem_7_param         (auto_tl_master_clock_xing_out_c_mem_7_param),
    .auto_out_c_mem_7_size          (auto_tl_master_clock_xing_out_c_mem_7_size),
    .auto_out_c_mem_7_source        (auto_tl_master_clock_xing_out_c_mem_7_source),
    .auto_out_c_mem_7_address       (auto_tl_master_clock_xing_out_c_mem_7_address),
    .auto_out_c_mem_7_data          (auto_tl_master_clock_xing_out_c_mem_7_data),
    .auto_out_c_ridx                (auto_tl_master_clock_xing_out_c_ridx),
    .auto_out_c_widx                (auto_tl_master_clock_xing_out_c_widx),
    .auto_out_c_safe_ridx_valid     (auto_tl_master_clock_xing_out_c_safe_ridx_valid),
    .auto_out_c_safe_widx_valid     (auto_tl_master_clock_xing_out_c_safe_widx_valid),
    .auto_out_c_safe_source_reset_n (auto_tl_master_clock_xing_out_c_safe_source_reset_n),
    .auto_out_c_safe_sink_reset_n   (auto_tl_master_clock_xing_out_c_safe_sink_reset_n),
    .auto_out_d_mem_0_opcode        (auto_tl_master_clock_xing_out_d_mem_0_opcode),
    .auto_out_d_mem_0_param         (auto_tl_master_clock_xing_out_d_mem_0_param),
    .auto_out_d_mem_0_size          (auto_tl_master_clock_xing_out_d_mem_0_size),
    .auto_out_d_mem_0_source        (auto_tl_master_clock_xing_out_d_mem_0_source),
    .auto_out_d_mem_0_sink          (auto_tl_master_clock_xing_out_d_mem_0_sink),
    .auto_out_d_mem_0_denied        (auto_tl_master_clock_xing_out_d_mem_0_denied),
    .auto_out_d_mem_0_data          (auto_tl_master_clock_xing_out_d_mem_0_data),
    .auto_out_d_mem_0_corrupt       (auto_tl_master_clock_xing_out_d_mem_0_corrupt),
    .auto_out_d_mem_1_opcode        (auto_tl_master_clock_xing_out_d_mem_1_opcode),
    .auto_out_d_mem_1_param         (auto_tl_master_clock_xing_out_d_mem_1_param),
    .auto_out_d_mem_1_size          (auto_tl_master_clock_xing_out_d_mem_1_size),
    .auto_out_d_mem_1_source        (auto_tl_master_clock_xing_out_d_mem_1_source),
    .auto_out_d_mem_1_sink          (auto_tl_master_clock_xing_out_d_mem_1_sink),
    .auto_out_d_mem_1_denied        (auto_tl_master_clock_xing_out_d_mem_1_denied),
    .auto_out_d_mem_1_data          (auto_tl_master_clock_xing_out_d_mem_1_data),
    .auto_out_d_mem_1_corrupt       (auto_tl_master_clock_xing_out_d_mem_1_corrupt),
    .auto_out_d_mem_2_opcode        (auto_tl_master_clock_xing_out_d_mem_2_opcode),
    .auto_out_d_mem_2_param         (auto_tl_master_clock_xing_out_d_mem_2_param),
    .auto_out_d_mem_2_size          (auto_tl_master_clock_xing_out_d_mem_2_size),
    .auto_out_d_mem_2_source        (auto_tl_master_clock_xing_out_d_mem_2_source),
    .auto_out_d_mem_2_sink          (auto_tl_master_clock_xing_out_d_mem_2_sink),
    .auto_out_d_mem_2_denied        (auto_tl_master_clock_xing_out_d_mem_2_denied),
    .auto_out_d_mem_2_data          (auto_tl_master_clock_xing_out_d_mem_2_data),
    .auto_out_d_mem_2_corrupt       (auto_tl_master_clock_xing_out_d_mem_2_corrupt),
    .auto_out_d_mem_3_opcode        (auto_tl_master_clock_xing_out_d_mem_3_opcode),
    .auto_out_d_mem_3_param         (auto_tl_master_clock_xing_out_d_mem_3_param),
    .auto_out_d_mem_3_size          (auto_tl_master_clock_xing_out_d_mem_3_size),
    .auto_out_d_mem_3_source        (auto_tl_master_clock_xing_out_d_mem_3_source),
    .auto_out_d_mem_3_sink          (auto_tl_master_clock_xing_out_d_mem_3_sink),
    .auto_out_d_mem_3_denied        (auto_tl_master_clock_xing_out_d_mem_3_denied),
    .auto_out_d_mem_3_data          (auto_tl_master_clock_xing_out_d_mem_3_data),
    .auto_out_d_mem_3_corrupt       (auto_tl_master_clock_xing_out_d_mem_3_corrupt),
    .auto_out_d_mem_4_opcode        (auto_tl_master_clock_xing_out_d_mem_4_opcode),
    .auto_out_d_mem_4_param         (auto_tl_master_clock_xing_out_d_mem_4_param),
    .auto_out_d_mem_4_size          (auto_tl_master_clock_xing_out_d_mem_4_size),
    .auto_out_d_mem_4_source        (auto_tl_master_clock_xing_out_d_mem_4_source),
    .auto_out_d_mem_4_sink          (auto_tl_master_clock_xing_out_d_mem_4_sink),
    .auto_out_d_mem_4_denied        (auto_tl_master_clock_xing_out_d_mem_4_denied),
    .auto_out_d_mem_4_data          (auto_tl_master_clock_xing_out_d_mem_4_data),
    .auto_out_d_mem_4_corrupt       (auto_tl_master_clock_xing_out_d_mem_4_corrupt),
    .auto_out_d_mem_5_opcode        (auto_tl_master_clock_xing_out_d_mem_5_opcode),
    .auto_out_d_mem_5_param         (auto_tl_master_clock_xing_out_d_mem_5_param),
    .auto_out_d_mem_5_size          (auto_tl_master_clock_xing_out_d_mem_5_size),
    .auto_out_d_mem_5_source        (auto_tl_master_clock_xing_out_d_mem_5_source),
    .auto_out_d_mem_5_sink          (auto_tl_master_clock_xing_out_d_mem_5_sink),
    .auto_out_d_mem_5_denied        (auto_tl_master_clock_xing_out_d_mem_5_denied),
    .auto_out_d_mem_5_data          (auto_tl_master_clock_xing_out_d_mem_5_data),
    .auto_out_d_mem_5_corrupt       (auto_tl_master_clock_xing_out_d_mem_5_corrupt),
    .auto_out_d_mem_6_opcode        (auto_tl_master_clock_xing_out_d_mem_6_opcode),
    .auto_out_d_mem_6_param         (auto_tl_master_clock_xing_out_d_mem_6_param),
    .auto_out_d_mem_6_size          (auto_tl_master_clock_xing_out_d_mem_6_size),
    .auto_out_d_mem_6_source        (auto_tl_master_clock_xing_out_d_mem_6_source),
    .auto_out_d_mem_6_sink          (auto_tl_master_clock_xing_out_d_mem_6_sink),
    .auto_out_d_mem_6_denied        (auto_tl_master_clock_xing_out_d_mem_6_denied),
    .auto_out_d_mem_6_data          (auto_tl_master_clock_xing_out_d_mem_6_data),
    .auto_out_d_mem_6_corrupt       (auto_tl_master_clock_xing_out_d_mem_6_corrupt),
    .auto_out_d_mem_7_opcode        (auto_tl_master_clock_xing_out_d_mem_7_opcode),
    .auto_out_d_mem_7_param         (auto_tl_master_clock_xing_out_d_mem_7_param),
    .auto_out_d_mem_7_size          (auto_tl_master_clock_xing_out_d_mem_7_size),
    .auto_out_d_mem_7_source        (auto_tl_master_clock_xing_out_d_mem_7_source),
    .auto_out_d_mem_7_sink          (auto_tl_master_clock_xing_out_d_mem_7_sink),
    .auto_out_d_mem_7_denied        (auto_tl_master_clock_xing_out_d_mem_7_denied),
    .auto_out_d_mem_7_data          (auto_tl_master_clock_xing_out_d_mem_7_data),
    .auto_out_d_mem_7_corrupt       (auto_tl_master_clock_xing_out_d_mem_7_corrupt),
    .auto_out_d_ridx                (auto_tl_master_clock_xing_out_d_ridx),
    .auto_out_d_widx                (auto_tl_master_clock_xing_out_d_widx),
    .auto_out_d_safe_ridx_valid     (auto_tl_master_clock_xing_out_d_safe_ridx_valid),
    .auto_out_d_safe_widx_valid     (auto_tl_master_clock_xing_out_d_safe_widx_valid),
    .auto_out_d_safe_source_reset_n (auto_tl_master_clock_xing_out_d_safe_source_reset_n),
    .auto_out_d_safe_sink_reset_n   (auto_tl_master_clock_xing_out_d_safe_sink_reset_n),
    .auto_out_e_mem_0_sink          (auto_tl_master_clock_xing_out_e_mem_0_sink),
    .auto_out_e_mem_1_sink          (auto_tl_master_clock_xing_out_e_mem_1_sink),
    .auto_out_e_mem_2_sink          (auto_tl_master_clock_xing_out_e_mem_2_sink),
    .auto_out_e_mem_3_sink          (auto_tl_master_clock_xing_out_e_mem_3_sink),
    .auto_out_e_mem_4_sink          (auto_tl_master_clock_xing_out_e_mem_4_sink),
    .auto_out_e_mem_5_sink          (auto_tl_master_clock_xing_out_e_mem_5_sink),
    .auto_out_e_mem_6_sink          (auto_tl_master_clock_xing_out_e_mem_6_sink),
    .auto_out_e_mem_7_sink          (auto_tl_master_clock_xing_out_e_mem_7_sink),
    .auto_out_e_ridx                (auto_tl_master_clock_xing_out_e_ridx),
    .auto_out_e_widx                (auto_tl_master_clock_xing_out_e_widx),
    .auto_out_e_safe_ridx_valid     (auto_tl_master_clock_xing_out_e_safe_ridx_valid),
    .auto_out_e_safe_widx_valid     (auto_tl_master_clock_xing_out_e_safe_widx_valid),
    .auto_out_e_safe_source_reset_n (auto_tl_master_clock_xing_out_e_safe_source_reset_n),
    .auto_out_e_safe_sink_reset_n   (auto_tl_master_clock_xing_out_e_safe_sink_reset_n)
  );
  IntSyncAsyncCrossingSink intsink (	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:80:29]
    .clock          (auto_tap_clock_in_clock),
    .auto_in_sync_0 (auto_intsink_in_sync_0),
    .auto_out_0     (_intsink_auto_out_0)
  );
  IntSyncAsyncCrossingSink_1 intsink_1 (	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:80:29]
    .clock          (auto_tap_clock_in_clock),
    .auto_in_sync_0 (auto_int_in_clock_xing_in_0_sync_0),
    .auto_in_sync_1 (auto_int_in_clock_xing_in_0_sync_1),
    .auto_out_0     (_intsink_1_auto_out_0),
    .auto_out_1     (_intsink_1_auto_out_1)
  );
  IntSyncAsyncCrossingSink intsink_2 (	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:80:29]
    .clock          (auto_tap_clock_in_clock),
    .auto_in_sync_0 (auto_int_in_clock_xing_in_1_sync_0),
    .auto_out_0     (_intsink_2_auto_out_0)
  );
  IntSyncAsyncCrossingSink intsink_3 (	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:80:29]
    .clock          (auto_tap_clock_in_clock),
    .auto_in_sync_0 (auto_int_in_clock_xing_in_2_sync_0),
    .auto_out_0     (_intsink_3_auto_out_0)
  );
  IntSyncCrossingSource intsource (	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:28:31]
    .clock           (auto_tap_clock_in_clock),
    .reset           (auto_tap_clock_in_reset),
    .auto_in_0       (1'h0),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18, generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:28:31, generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59, generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
    .auto_out_sync_0 (/* unused */)
  );
  IntSyncCrossingSource intsource_1 (	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:28:31]
    .clock           (auto_tap_clock_in_clock),
    .reset           (auto_tap_clock_in_reset),
    .auto_in_0       (_element_reset_domain_rockettile_auto_wfi_out_0),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59]
    .auto_out_sync_0 (/* unused */)
  );
  IntSyncCrossingSource intsource_2 (	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:28:31]
    .clock           (auto_tap_clock_in_clock),
    .reset           (auto_tap_clock_in_reset),
    .auto_in_0       (1'h0),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18, generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:28:31, generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:161:59, generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:89:29]
    .auto_out_sync_0 (/* unused */)
  );
endmodule

