// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module TileResetSetter(
  input         clock,
                reset,
                auto_clock_in_member_allClocks_tileClockGroup_rockettile_2_clock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_clock_in_member_allClocks_tileClockGroup_rockettile_2_reset,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_clock_in_member_allClocks_tileClockGroup_rockettile_1_clock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_clock_in_member_allClocks_tileClockGroup_rockettile_1_reset,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_clock_in_member_allClocks_tileClockGroup_rockettile_0_clock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_clock_in_member_allClocks_tileClockGroup_rockettile_0_reset,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_clock_in_member_allClocks_uncore_clock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_clock_in_member_allClocks_uncore_reset,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_clock_out_member_allClocks_tileClockGroup_rockettile_2_clock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_clock_out_member_allClocks_tileClockGroup_rockettile_2_reset,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_clock_out_member_allClocks_tileClockGroup_rockettile_1_clock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_clock_out_member_allClocks_tileClockGroup_rockettile_1_reset,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_clock_out_member_allClocks_tileClockGroup_rockettile_0_clock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_clock_out_member_allClocks_tileClockGroup_rockettile_0_reset,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_clock_out_member_allClocks_uncore_clock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_clock_out_member_allClocks_uncore_reset,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_tl_in_a_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_tl_in_a_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_tl_in_a_bits_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_tl_in_a_bits_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]  auto_tl_in_a_bits_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [13:0] auto_tl_in_a_bits_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [20:0] auto_tl_in_a_bits_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_tl_in_a_bits_mask,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_tl_in_a_bits_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_tl_in_a_bits_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_tl_in_d_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_tl_in_d_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]  auto_tl_in_d_bits_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_tl_in_d_bits_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [13:0] auto_tl_in_d_bits_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0] auto_tl_in_d_bits_data	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
);

  wire       out_woready_1;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
  wire       _out_wofireMux_T_2;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
  wire       out_iindex;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
  wire       _r_tile_resets_2_io_q;	// @[generators/chipyard/src/main/scala/clocking/TileResetSetter.scala:33:15]
  wire       _r_tile_resets_1_io_q;	// @[generators/chipyard/src/main/scala/clocking/TileResetSetter.scala:33:15]
  wire       _r_tile_resets_0_io_q;	// @[generators/chipyard/src/main/scala/clocking/TileResetSetter.scala:33:15]
  wire       out_front_bits_read = auto_tl_in_a_bits_opcode == 3'h4;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:69:36]
  wire       _out_out_bits_data_WIRE_1 = auto_tl_in_a_bits_address[11:4] == 8'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:193:34, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:70:19, :82:24]
  assign out_iindex = auto_tl_in_a_bits_address[3];	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
  assign _out_wofireMux_T_2 = auto_tl_in_a_valid & auto_tl_in_d_ready & ~out_front_bits_read;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:69:36, :82:24]
  assign out_woready_1 = _out_wofireMux_T_2 & ~out_iindex & _out_out_bits_data_WIRE_1;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
  wire [2:0] tlNodeIn_d_bits_opcode = {2'h0, out_front_bits_read};	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:69:36, :100:19]
  TLMonitor_69 monitor (	// @[generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:24:25]
    .clock                (clock),
    .reset                (reset),
    .io_in_a_ready        (auto_tl_in_d_ready),
    .io_in_a_valid        (auto_tl_in_a_valid),
    .io_in_a_bits_opcode  (auto_tl_in_a_bits_opcode),
    .io_in_a_bits_param   (auto_tl_in_a_bits_param),
    .io_in_a_bits_size    (auto_tl_in_a_bits_size),
    .io_in_a_bits_source  (auto_tl_in_a_bits_source),
    .io_in_a_bits_address (auto_tl_in_a_bits_address),
    .io_in_a_bits_mask    (auto_tl_in_a_bits_mask),
    .io_in_a_bits_corrupt (auto_tl_in_a_bits_corrupt),
    .io_in_d_ready        (auto_tl_in_d_ready),
    .io_in_d_valid        (auto_tl_in_a_valid),
    .io_in_d_bits_opcode  (tlNodeIn_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:100:19]
    .io_in_d_bits_size    (auto_tl_in_a_bits_size),
    .io_in_d_bits_source  (auto_tl_in_a_bits_source)
  );
  AsyncResetRegVec_w1_i0_16 r_tile_resets_0 (	// @[generators/chipyard/src/main/scala/clocking/TileResetSetter.scala:33:15]
    .clock (clock),
    .reset (auto_clock_in_member_allClocks_tileClockGroup_rockettile_0_reset),
    .io_d  (auto_tl_in_a_bits_data[0]),	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
    .io_q  (_r_tile_resets_0_io_q),
    .io_en (out_woready_1 & auto_tl_in_a_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
  );
  AsyncResetRegVec_w1_i0_16 r_tile_resets_1 (	// @[generators/chipyard/src/main/scala/clocking/TileResetSetter.scala:33:15]
    .clock (clock),
    .reset (auto_clock_in_member_allClocks_tileClockGroup_rockettile_1_reset),
    .io_d  (auto_tl_in_a_bits_data[32]),	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
    .io_q  (_r_tile_resets_1_io_q),
    .io_en (out_woready_1 & auto_tl_in_a_bits_mask[4])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
  );
  AsyncResetRegVec_w1_i0_16 r_tile_resets_2 (	// @[generators/chipyard/src/main/scala/clocking/TileResetSetter.scala:33:15]
    .clock (clock),
    .reset (auto_clock_in_member_allClocks_tileClockGroup_rockettile_2_reset),
    .io_d  (auto_tl_in_a_bits_data[0]),	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
    .io_q  (_r_tile_resets_2_io_q),
    .io_en (_out_wofireMux_T_2 & out_iindex & _out_out_bits_data_WIRE_1 & auto_tl_in_a_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
  );
  assign auto_clock_out_member_allClocks_tileClockGroup_rockettile_2_clock = auto_clock_in_member_allClocks_tileClockGroup_rockettile_2_clock;
  assign auto_clock_out_member_allClocks_tileClockGroup_rockettile_2_reset = _r_tile_resets_2_io_q | auto_clock_in_member_allClocks_tileClockGroup_rockettile_2_reset;	// @[generators/chipyard/src/main/scala/clocking/TileResetSetter.scala:33:15, :57:38]
  assign auto_clock_out_member_allClocks_tileClockGroup_rockettile_1_clock = auto_clock_in_member_allClocks_tileClockGroup_rockettile_1_clock;
  assign auto_clock_out_member_allClocks_tileClockGroup_rockettile_1_reset = _r_tile_resets_1_io_q | auto_clock_in_member_allClocks_tileClockGroup_rockettile_1_reset;	// @[generators/chipyard/src/main/scala/clocking/TileResetSetter.scala:33:15, :57:38]
  assign auto_clock_out_member_allClocks_tileClockGroup_rockettile_0_clock = auto_clock_in_member_allClocks_tileClockGroup_rockettile_0_clock;
  assign auto_clock_out_member_allClocks_tileClockGroup_rockettile_0_reset = _r_tile_resets_0_io_q | auto_clock_in_member_allClocks_tileClockGroup_rockettile_0_reset;	// @[generators/chipyard/src/main/scala/clocking/TileResetSetter.scala:33:15, :57:38]
  assign auto_clock_out_member_allClocks_uncore_clock = auto_clock_in_member_allClocks_uncore_clock;
  assign auto_clock_out_member_allClocks_uncore_reset = auto_clock_in_member_allClocks_uncore_reset;
  assign auto_tl_in_a_ready = auto_tl_in_d_ready;
  assign auto_tl_in_d_valid = auto_tl_in_a_valid;
  assign auto_tl_in_d_bits_opcode = tlNodeIn_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:100:19]
  assign auto_tl_in_d_bits_size = auto_tl_in_a_bits_size;
  assign auto_tl_in_d_bits_source = auto_tl_in_a_bits_source;
  assign auto_tl_in_d_bits_data = {31'h0, _out_out_bits_data_WIRE_1 ? (out_iindex ? {32'h0, _r_tile_resets_2_io_q} : {_r_tile_resets_1_io_q, 31'h0, _r_tile_resets_0_io_q}) : 33'h0};	// @[generators/chipyard/src/main/scala/clocking/TileResetSetter.scala:33:15, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:49:{10,48}]
endmodule

