// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module TLAsyncCrossingSink(
  input         clock,
                reset,
  input  [2:0]  auto_in_a_mem_0_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_in_a_mem_0_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_in_a_mem_0_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]  auto_in_a_mem_0_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_in_a_mem_0_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_in_a_mem_0_mask,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_in_a_mem_0_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_in_a_mem_1_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_in_a_mem_1_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_in_a_mem_1_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]  auto_in_a_mem_1_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_in_a_mem_1_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_in_a_mem_1_mask,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_in_a_mem_1_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_in_a_mem_2_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_in_a_mem_2_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_in_a_mem_2_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]  auto_in_a_mem_2_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_in_a_mem_2_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_in_a_mem_2_mask,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_in_a_mem_2_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_in_a_mem_3_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_in_a_mem_3_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_in_a_mem_3_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]  auto_in_a_mem_3_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_in_a_mem_3_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_in_a_mem_3_mask,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_in_a_mem_3_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_in_a_mem_4_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_in_a_mem_4_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_in_a_mem_4_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]  auto_in_a_mem_4_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_in_a_mem_4_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_in_a_mem_4_mask,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_in_a_mem_4_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_in_a_mem_5_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_in_a_mem_5_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_in_a_mem_5_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]  auto_in_a_mem_5_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_in_a_mem_5_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_in_a_mem_5_mask,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_in_a_mem_5_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_in_a_mem_6_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_in_a_mem_6_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_in_a_mem_6_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]  auto_in_a_mem_6_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_in_a_mem_6_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_in_a_mem_6_mask,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_in_a_mem_6_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_in_a_mem_7_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_in_a_mem_7_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_in_a_mem_7_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]  auto_in_a_mem_7_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_in_a_mem_7_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_in_a_mem_7_mask,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_in_a_mem_7_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_in_a_ridx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_in_a_widx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_in_a_safe_ridx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_in_a_safe_widx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_in_a_safe_source_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_in_a_safe_sink_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_in_b_mem_0_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]  auto_in_b_mem_0_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0] auto_in_b_mem_0_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_in_b_mem_1_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]  auto_in_b_mem_1_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0] auto_in_b_mem_1_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_in_b_mem_2_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]  auto_in_b_mem_2_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0] auto_in_b_mem_2_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_in_b_mem_3_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]  auto_in_b_mem_3_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0] auto_in_b_mem_3_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_in_b_mem_4_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]  auto_in_b_mem_4_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0] auto_in_b_mem_4_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_in_b_mem_5_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]  auto_in_b_mem_5_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0] auto_in_b_mem_5_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_in_b_mem_6_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]  auto_in_b_mem_6_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0] auto_in_b_mem_6_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_in_b_mem_7_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]  auto_in_b_mem_7_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0] auto_in_b_mem_7_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_in_b_ridx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_in_b_widx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_in_b_safe_ridx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_in_b_safe_widx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_in_b_safe_source_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_in_b_safe_sink_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_in_c_mem_0_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_in_c_mem_0_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_in_c_mem_0_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]  auto_in_c_mem_0_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_in_c_mem_0_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_in_c_mem_0_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_in_c_mem_1_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_in_c_mem_1_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_in_c_mem_1_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]  auto_in_c_mem_1_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_in_c_mem_1_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_in_c_mem_1_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_in_c_mem_2_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_in_c_mem_2_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_in_c_mem_2_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]  auto_in_c_mem_2_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_in_c_mem_2_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_in_c_mem_2_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_in_c_mem_3_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_in_c_mem_3_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_in_c_mem_3_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]  auto_in_c_mem_3_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_in_c_mem_3_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_in_c_mem_3_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_in_c_mem_4_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_in_c_mem_4_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_in_c_mem_4_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]  auto_in_c_mem_4_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_in_c_mem_4_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_in_c_mem_4_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_in_c_mem_5_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_in_c_mem_5_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_in_c_mem_5_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]  auto_in_c_mem_5_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_in_c_mem_5_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_in_c_mem_5_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_in_c_mem_6_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_in_c_mem_6_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_in_c_mem_6_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]  auto_in_c_mem_6_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_in_c_mem_6_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_in_c_mem_6_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_in_c_mem_7_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_in_c_mem_7_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_in_c_mem_7_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]  auto_in_c_mem_7_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_in_c_mem_7_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_in_c_mem_7_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_in_c_ridx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_in_c_widx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_in_c_safe_ridx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_in_c_safe_widx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_in_c_safe_source_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_in_c_safe_sink_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]  auto_in_d_mem_0_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_in_d_mem_0_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_in_d_mem_0_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]  auto_in_d_mem_0_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]  auto_in_d_mem_0_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_in_d_mem_0_denied,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0] auto_in_d_mem_0_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_in_d_mem_0_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]  auto_in_d_mem_1_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_in_d_mem_1_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_in_d_mem_1_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]  auto_in_d_mem_1_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]  auto_in_d_mem_1_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_in_d_mem_1_denied,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0] auto_in_d_mem_1_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_in_d_mem_1_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]  auto_in_d_mem_2_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_in_d_mem_2_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_in_d_mem_2_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]  auto_in_d_mem_2_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]  auto_in_d_mem_2_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_in_d_mem_2_denied,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0] auto_in_d_mem_2_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_in_d_mem_2_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]  auto_in_d_mem_3_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_in_d_mem_3_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_in_d_mem_3_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]  auto_in_d_mem_3_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]  auto_in_d_mem_3_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_in_d_mem_3_denied,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0] auto_in_d_mem_3_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_in_d_mem_3_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]  auto_in_d_mem_4_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_in_d_mem_4_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_in_d_mem_4_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]  auto_in_d_mem_4_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]  auto_in_d_mem_4_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_in_d_mem_4_denied,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0] auto_in_d_mem_4_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_in_d_mem_4_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]  auto_in_d_mem_5_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_in_d_mem_5_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_in_d_mem_5_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]  auto_in_d_mem_5_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]  auto_in_d_mem_5_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_in_d_mem_5_denied,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0] auto_in_d_mem_5_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_in_d_mem_5_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]  auto_in_d_mem_6_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_in_d_mem_6_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_in_d_mem_6_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]  auto_in_d_mem_6_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]  auto_in_d_mem_6_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_in_d_mem_6_denied,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0] auto_in_d_mem_6_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_in_d_mem_6_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]  auto_in_d_mem_7_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_in_d_mem_7_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_in_d_mem_7_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]  auto_in_d_mem_7_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]  auto_in_d_mem_7_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_in_d_mem_7_denied,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0] auto_in_d_mem_7_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_in_d_mem_7_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_in_d_ridx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_in_d_widx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_in_d_safe_ridx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_in_d_safe_widx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_in_d_safe_source_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_in_d_safe_sink_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_in_e_mem_0_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_in_e_mem_1_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_in_e_mem_2_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_in_e_mem_3_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_in_e_mem_4_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_in_e_mem_5_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_in_e_mem_6_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_in_e_mem_7_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_in_e_ridx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_in_e_widx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_in_e_safe_ridx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_in_e_safe_widx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_in_e_safe_source_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_in_e_safe_sink_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_out_a_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_out_a_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]  auto_out_a_bits_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_out_a_bits_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_out_a_bits_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]  auto_out_a_bits_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0] auto_out_a_bits_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [7:0]  auto_out_a_bits_mask,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0] auto_out_a_bits_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_out_a_bits_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_out_b_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_out_b_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]  auto_out_b_bits_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]  auto_out_b_bits_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_out_b_bits_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_out_c_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_out_c_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]  auto_out_c_bits_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_out_c_bits_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_out_c_bits_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [5:0]  auto_out_c_bits_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0] auto_out_c_bits_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0] auto_out_c_bits_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_out_c_bits_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_out_d_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_out_d_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_out_d_bits_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]  auto_out_d_bits_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_out_d_bits_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [5:0]  auto_out_d_bits_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_out_d_bits_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_out_d_bits_denied,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_out_d_bits_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_out_d_bits_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_out_e_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_out_e_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]  auto_out_e_bits_sink	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
);

  AsyncQueueSink nodeOut_a_sink (	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:207:22]
    .clock                        (clock),
    .reset                        (reset),
    .io_deq_ready                 (auto_out_a_ready),
    .io_deq_valid                 (auto_out_a_valid),
    .io_deq_bits_opcode           (auto_out_a_bits_opcode),
    .io_deq_bits_param            (auto_out_a_bits_param),
    .io_deq_bits_size             (auto_out_a_bits_size),
    .io_deq_bits_source           (auto_out_a_bits_source),
    .io_deq_bits_address          (auto_out_a_bits_address),
    .io_deq_bits_mask             (auto_out_a_bits_mask),
    .io_deq_bits_data             (auto_out_a_bits_data),
    .io_deq_bits_corrupt          (auto_out_a_bits_corrupt),
    .io_async_mem_0_opcode        (auto_in_a_mem_0_opcode),
    .io_async_mem_0_param         (auto_in_a_mem_0_param),
    .io_async_mem_0_size          (auto_in_a_mem_0_size),
    .io_async_mem_0_source        (auto_in_a_mem_0_source),
    .io_async_mem_0_address       (auto_in_a_mem_0_address),
    .io_async_mem_0_mask          (auto_in_a_mem_0_mask),
    .io_async_mem_0_data          (auto_in_a_mem_0_data),
    .io_async_mem_1_opcode        (auto_in_a_mem_1_opcode),
    .io_async_mem_1_param         (auto_in_a_mem_1_param),
    .io_async_mem_1_size          (auto_in_a_mem_1_size),
    .io_async_mem_1_source        (auto_in_a_mem_1_source),
    .io_async_mem_1_address       (auto_in_a_mem_1_address),
    .io_async_mem_1_mask          (auto_in_a_mem_1_mask),
    .io_async_mem_1_data          (auto_in_a_mem_1_data),
    .io_async_mem_2_opcode        (auto_in_a_mem_2_opcode),
    .io_async_mem_2_param         (auto_in_a_mem_2_param),
    .io_async_mem_2_size          (auto_in_a_mem_2_size),
    .io_async_mem_2_source        (auto_in_a_mem_2_source),
    .io_async_mem_2_address       (auto_in_a_mem_2_address),
    .io_async_mem_2_mask          (auto_in_a_mem_2_mask),
    .io_async_mem_2_data          (auto_in_a_mem_2_data),
    .io_async_mem_3_opcode        (auto_in_a_mem_3_opcode),
    .io_async_mem_3_param         (auto_in_a_mem_3_param),
    .io_async_mem_3_size          (auto_in_a_mem_3_size),
    .io_async_mem_3_source        (auto_in_a_mem_3_source),
    .io_async_mem_3_address       (auto_in_a_mem_3_address),
    .io_async_mem_3_mask          (auto_in_a_mem_3_mask),
    .io_async_mem_3_data          (auto_in_a_mem_3_data),
    .io_async_mem_4_opcode        (auto_in_a_mem_4_opcode),
    .io_async_mem_4_param         (auto_in_a_mem_4_param),
    .io_async_mem_4_size          (auto_in_a_mem_4_size),
    .io_async_mem_4_source        (auto_in_a_mem_4_source),
    .io_async_mem_4_address       (auto_in_a_mem_4_address),
    .io_async_mem_4_mask          (auto_in_a_mem_4_mask),
    .io_async_mem_4_data          (auto_in_a_mem_4_data),
    .io_async_mem_5_opcode        (auto_in_a_mem_5_opcode),
    .io_async_mem_5_param         (auto_in_a_mem_5_param),
    .io_async_mem_5_size          (auto_in_a_mem_5_size),
    .io_async_mem_5_source        (auto_in_a_mem_5_source),
    .io_async_mem_5_address       (auto_in_a_mem_5_address),
    .io_async_mem_5_mask          (auto_in_a_mem_5_mask),
    .io_async_mem_5_data          (auto_in_a_mem_5_data),
    .io_async_mem_6_opcode        (auto_in_a_mem_6_opcode),
    .io_async_mem_6_param         (auto_in_a_mem_6_param),
    .io_async_mem_6_size          (auto_in_a_mem_6_size),
    .io_async_mem_6_source        (auto_in_a_mem_6_source),
    .io_async_mem_6_address       (auto_in_a_mem_6_address),
    .io_async_mem_6_mask          (auto_in_a_mem_6_mask),
    .io_async_mem_6_data          (auto_in_a_mem_6_data),
    .io_async_mem_7_opcode        (auto_in_a_mem_7_opcode),
    .io_async_mem_7_param         (auto_in_a_mem_7_param),
    .io_async_mem_7_size          (auto_in_a_mem_7_size),
    .io_async_mem_7_source        (auto_in_a_mem_7_source),
    .io_async_mem_7_address       (auto_in_a_mem_7_address),
    .io_async_mem_7_mask          (auto_in_a_mem_7_mask),
    .io_async_mem_7_data          (auto_in_a_mem_7_data),
    .io_async_ridx                (auto_in_a_ridx),
    .io_async_widx                (auto_in_a_widx),
    .io_async_safe_ridx_valid     (auto_in_a_safe_ridx_valid),
    .io_async_safe_widx_valid     (auto_in_a_safe_widx_valid),
    .io_async_safe_source_reset_n (auto_in_a_safe_source_reset_n),
    .io_async_safe_sink_reset_n   (auto_in_a_safe_sink_reset_n)
  );
  AsyncQueueSource nodeIn_d_source (	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:216:24]
    .clock                        (clock),
    .reset                        (reset),
    .io_enq_ready                 (auto_out_d_ready),
    .io_enq_valid                 (auto_out_d_valid),
    .io_enq_bits_opcode           (auto_out_d_bits_opcode),
    .io_enq_bits_param            (auto_out_d_bits_param),
    .io_enq_bits_size             (auto_out_d_bits_size),
    .io_enq_bits_source           (auto_out_d_bits_source),
    .io_enq_bits_sink             (auto_out_d_bits_sink),
    .io_enq_bits_denied           (auto_out_d_bits_denied),
    .io_enq_bits_data             (auto_out_d_bits_data),
    .io_enq_bits_corrupt          (auto_out_d_bits_corrupt),
    .io_async_mem_0_opcode        (auto_in_d_mem_0_opcode),
    .io_async_mem_0_param         (auto_in_d_mem_0_param),
    .io_async_mem_0_size          (auto_in_d_mem_0_size),
    .io_async_mem_0_source        (auto_in_d_mem_0_source),
    .io_async_mem_0_sink          (auto_in_d_mem_0_sink),
    .io_async_mem_0_denied        (auto_in_d_mem_0_denied),
    .io_async_mem_0_data          (auto_in_d_mem_0_data),
    .io_async_mem_0_corrupt       (auto_in_d_mem_0_corrupt),
    .io_async_mem_1_opcode        (auto_in_d_mem_1_opcode),
    .io_async_mem_1_param         (auto_in_d_mem_1_param),
    .io_async_mem_1_size          (auto_in_d_mem_1_size),
    .io_async_mem_1_source        (auto_in_d_mem_1_source),
    .io_async_mem_1_sink          (auto_in_d_mem_1_sink),
    .io_async_mem_1_denied        (auto_in_d_mem_1_denied),
    .io_async_mem_1_data          (auto_in_d_mem_1_data),
    .io_async_mem_1_corrupt       (auto_in_d_mem_1_corrupt),
    .io_async_mem_2_opcode        (auto_in_d_mem_2_opcode),
    .io_async_mem_2_param         (auto_in_d_mem_2_param),
    .io_async_mem_2_size          (auto_in_d_mem_2_size),
    .io_async_mem_2_source        (auto_in_d_mem_2_source),
    .io_async_mem_2_sink          (auto_in_d_mem_2_sink),
    .io_async_mem_2_denied        (auto_in_d_mem_2_denied),
    .io_async_mem_2_data          (auto_in_d_mem_2_data),
    .io_async_mem_2_corrupt       (auto_in_d_mem_2_corrupt),
    .io_async_mem_3_opcode        (auto_in_d_mem_3_opcode),
    .io_async_mem_3_param         (auto_in_d_mem_3_param),
    .io_async_mem_3_size          (auto_in_d_mem_3_size),
    .io_async_mem_3_source        (auto_in_d_mem_3_source),
    .io_async_mem_3_sink          (auto_in_d_mem_3_sink),
    .io_async_mem_3_denied        (auto_in_d_mem_3_denied),
    .io_async_mem_3_data          (auto_in_d_mem_3_data),
    .io_async_mem_3_corrupt       (auto_in_d_mem_3_corrupt),
    .io_async_mem_4_opcode        (auto_in_d_mem_4_opcode),
    .io_async_mem_4_param         (auto_in_d_mem_4_param),
    .io_async_mem_4_size          (auto_in_d_mem_4_size),
    .io_async_mem_4_source        (auto_in_d_mem_4_source),
    .io_async_mem_4_sink          (auto_in_d_mem_4_sink),
    .io_async_mem_4_denied        (auto_in_d_mem_4_denied),
    .io_async_mem_4_data          (auto_in_d_mem_4_data),
    .io_async_mem_4_corrupt       (auto_in_d_mem_4_corrupt),
    .io_async_mem_5_opcode        (auto_in_d_mem_5_opcode),
    .io_async_mem_5_param         (auto_in_d_mem_5_param),
    .io_async_mem_5_size          (auto_in_d_mem_5_size),
    .io_async_mem_5_source        (auto_in_d_mem_5_source),
    .io_async_mem_5_sink          (auto_in_d_mem_5_sink),
    .io_async_mem_5_denied        (auto_in_d_mem_5_denied),
    .io_async_mem_5_data          (auto_in_d_mem_5_data),
    .io_async_mem_5_corrupt       (auto_in_d_mem_5_corrupt),
    .io_async_mem_6_opcode        (auto_in_d_mem_6_opcode),
    .io_async_mem_6_param         (auto_in_d_mem_6_param),
    .io_async_mem_6_size          (auto_in_d_mem_6_size),
    .io_async_mem_6_source        (auto_in_d_mem_6_source),
    .io_async_mem_6_sink          (auto_in_d_mem_6_sink),
    .io_async_mem_6_denied        (auto_in_d_mem_6_denied),
    .io_async_mem_6_data          (auto_in_d_mem_6_data),
    .io_async_mem_6_corrupt       (auto_in_d_mem_6_corrupt),
    .io_async_mem_7_opcode        (auto_in_d_mem_7_opcode),
    .io_async_mem_7_param         (auto_in_d_mem_7_param),
    .io_async_mem_7_size          (auto_in_d_mem_7_size),
    .io_async_mem_7_source        (auto_in_d_mem_7_source),
    .io_async_mem_7_sink          (auto_in_d_mem_7_sink),
    .io_async_mem_7_denied        (auto_in_d_mem_7_denied),
    .io_async_mem_7_data          (auto_in_d_mem_7_data),
    .io_async_mem_7_corrupt       (auto_in_d_mem_7_corrupt),
    .io_async_ridx                (auto_in_d_ridx),
    .io_async_widx                (auto_in_d_widx),
    .io_async_safe_ridx_valid     (auto_in_d_safe_ridx_valid),
    .io_async_safe_widx_valid     (auto_in_d_safe_widx_valid),
    .io_async_safe_source_reset_n (auto_in_d_safe_source_reset_n),
    .io_async_safe_sink_reset_n   (auto_in_d_safe_sink_reset_n)
  );
  AsyncQueueSource_1 nodeIn_b_source (	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:216:24]
    .clock                        (clock),
    .reset                        (reset),
    .io_enq_ready                 (auto_out_b_ready),
    .io_enq_valid                 (auto_out_b_valid),
    .io_enq_bits_param            (auto_out_b_bits_param),
    .io_enq_bits_source           (auto_out_b_bits_source),
    .io_enq_bits_address          (auto_out_b_bits_address),
    .io_async_mem_0_param         (auto_in_b_mem_0_param),
    .io_async_mem_0_source        (auto_in_b_mem_0_source),
    .io_async_mem_0_address       (auto_in_b_mem_0_address),
    .io_async_mem_1_param         (auto_in_b_mem_1_param),
    .io_async_mem_1_source        (auto_in_b_mem_1_source),
    .io_async_mem_1_address       (auto_in_b_mem_1_address),
    .io_async_mem_2_param         (auto_in_b_mem_2_param),
    .io_async_mem_2_source        (auto_in_b_mem_2_source),
    .io_async_mem_2_address       (auto_in_b_mem_2_address),
    .io_async_mem_3_param         (auto_in_b_mem_3_param),
    .io_async_mem_3_source        (auto_in_b_mem_3_source),
    .io_async_mem_3_address       (auto_in_b_mem_3_address),
    .io_async_mem_4_param         (auto_in_b_mem_4_param),
    .io_async_mem_4_source        (auto_in_b_mem_4_source),
    .io_async_mem_4_address       (auto_in_b_mem_4_address),
    .io_async_mem_5_param         (auto_in_b_mem_5_param),
    .io_async_mem_5_source        (auto_in_b_mem_5_source),
    .io_async_mem_5_address       (auto_in_b_mem_5_address),
    .io_async_mem_6_param         (auto_in_b_mem_6_param),
    .io_async_mem_6_source        (auto_in_b_mem_6_source),
    .io_async_mem_6_address       (auto_in_b_mem_6_address),
    .io_async_mem_7_param         (auto_in_b_mem_7_param),
    .io_async_mem_7_source        (auto_in_b_mem_7_source),
    .io_async_mem_7_address       (auto_in_b_mem_7_address),
    .io_async_ridx                (auto_in_b_ridx),
    .io_async_widx                (auto_in_b_widx),
    .io_async_safe_ridx_valid     (auto_in_b_safe_ridx_valid),
    .io_async_safe_widx_valid     (auto_in_b_safe_widx_valid),
    .io_async_safe_source_reset_n (auto_in_b_safe_source_reset_n),
    .io_async_safe_sink_reset_n   (auto_in_b_safe_sink_reset_n)
  );
  AsyncQueueSink_1 nodeOut_c_sink (	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:207:22]
    .clock                        (clock),
    .reset                        (reset),
    .io_deq_ready                 (auto_out_c_ready),
    .io_deq_valid                 (auto_out_c_valid),
    .io_deq_bits_opcode           (auto_out_c_bits_opcode),
    .io_deq_bits_param            (auto_out_c_bits_param),
    .io_deq_bits_size             (auto_out_c_bits_size),
    .io_deq_bits_source           (auto_out_c_bits_source),
    .io_deq_bits_address          (auto_out_c_bits_address),
    .io_deq_bits_data             (auto_out_c_bits_data),
    .io_deq_bits_corrupt          (auto_out_c_bits_corrupt),
    .io_async_mem_0_opcode        (auto_in_c_mem_0_opcode),
    .io_async_mem_0_param         (auto_in_c_mem_0_param),
    .io_async_mem_0_size          (auto_in_c_mem_0_size),
    .io_async_mem_0_source        (auto_in_c_mem_0_source),
    .io_async_mem_0_address       (auto_in_c_mem_0_address),
    .io_async_mem_0_data          (auto_in_c_mem_0_data),
    .io_async_mem_1_opcode        (auto_in_c_mem_1_opcode),
    .io_async_mem_1_param         (auto_in_c_mem_1_param),
    .io_async_mem_1_size          (auto_in_c_mem_1_size),
    .io_async_mem_1_source        (auto_in_c_mem_1_source),
    .io_async_mem_1_address       (auto_in_c_mem_1_address),
    .io_async_mem_1_data          (auto_in_c_mem_1_data),
    .io_async_mem_2_opcode        (auto_in_c_mem_2_opcode),
    .io_async_mem_2_param         (auto_in_c_mem_2_param),
    .io_async_mem_2_size          (auto_in_c_mem_2_size),
    .io_async_mem_2_source        (auto_in_c_mem_2_source),
    .io_async_mem_2_address       (auto_in_c_mem_2_address),
    .io_async_mem_2_data          (auto_in_c_mem_2_data),
    .io_async_mem_3_opcode        (auto_in_c_mem_3_opcode),
    .io_async_mem_3_param         (auto_in_c_mem_3_param),
    .io_async_mem_3_size          (auto_in_c_mem_3_size),
    .io_async_mem_3_source        (auto_in_c_mem_3_source),
    .io_async_mem_3_address       (auto_in_c_mem_3_address),
    .io_async_mem_3_data          (auto_in_c_mem_3_data),
    .io_async_mem_4_opcode        (auto_in_c_mem_4_opcode),
    .io_async_mem_4_param         (auto_in_c_mem_4_param),
    .io_async_mem_4_size          (auto_in_c_mem_4_size),
    .io_async_mem_4_source        (auto_in_c_mem_4_source),
    .io_async_mem_4_address       (auto_in_c_mem_4_address),
    .io_async_mem_4_data          (auto_in_c_mem_4_data),
    .io_async_mem_5_opcode        (auto_in_c_mem_5_opcode),
    .io_async_mem_5_param         (auto_in_c_mem_5_param),
    .io_async_mem_5_size          (auto_in_c_mem_5_size),
    .io_async_mem_5_source        (auto_in_c_mem_5_source),
    .io_async_mem_5_address       (auto_in_c_mem_5_address),
    .io_async_mem_5_data          (auto_in_c_mem_5_data),
    .io_async_mem_6_opcode        (auto_in_c_mem_6_opcode),
    .io_async_mem_6_param         (auto_in_c_mem_6_param),
    .io_async_mem_6_size          (auto_in_c_mem_6_size),
    .io_async_mem_6_source        (auto_in_c_mem_6_source),
    .io_async_mem_6_address       (auto_in_c_mem_6_address),
    .io_async_mem_6_data          (auto_in_c_mem_6_data),
    .io_async_mem_7_opcode        (auto_in_c_mem_7_opcode),
    .io_async_mem_7_param         (auto_in_c_mem_7_param),
    .io_async_mem_7_size          (auto_in_c_mem_7_size),
    .io_async_mem_7_source        (auto_in_c_mem_7_source),
    .io_async_mem_7_address       (auto_in_c_mem_7_address),
    .io_async_mem_7_data          (auto_in_c_mem_7_data),
    .io_async_ridx                (auto_in_c_ridx),
    .io_async_widx                (auto_in_c_widx),
    .io_async_safe_ridx_valid     (auto_in_c_safe_ridx_valid),
    .io_async_safe_widx_valid     (auto_in_c_safe_widx_valid),
    .io_async_safe_source_reset_n (auto_in_c_safe_source_reset_n),
    .io_async_safe_sink_reset_n   (auto_in_c_safe_sink_reset_n)
  );
  AsyncQueueSink_2 nodeOut_e_sink (	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:207:22]
    .clock                        (clock),
    .reset                        (reset),
    .io_deq_ready                 (auto_out_e_ready),
    .io_deq_valid                 (auto_out_e_valid),
    .io_deq_bits_sink             (auto_out_e_bits_sink),
    .io_async_mem_0_sink          (auto_in_e_mem_0_sink),
    .io_async_mem_1_sink          (auto_in_e_mem_1_sink),
    .io_async_mem_2_sink          (auto_in_e_mem_2_sink),
    .io_async_mem_3_sink          (auto_in_e_mem_3_sink),
    .io_async_mem_4_sink          (auto_in_e_mem_4_sink),
    .io_async_mem_5_sink          (auto_in_e_mem_5_sink),
    .io_async_mem_6_sink          (auto_in_e_mem_6_sink),
    .io_async_mem_7_sink          (auto_in_e_mem_7_sink),
    .io_async_ridx                (auto_in_e_ridx),
    .io_async_widx                (auto_in_e_widx),
    .io_async_safe_ridx_valid     (auto_in_e_safe_ridx_valid),
    .io_async_safe_widx_valid     (auto_in_e_safe_widx_valid),
    .io_async_safe_source_reset_n (auto_in_e_safe_source_reset_n),
    .io_async_safe_sink_reset_n   (auto_in_e_safe_sink_reset_n)
  );
endmodule

